### ISSUE TITLE
EventEmitter definition

### ISSUE THREAD

**Issue by XVincentX** [amireh/happypack#10]
Hello, and first of all, thank you for the project. I am really hoping this could speed up my compilation times.

For some strange reasons, I am stuck on node 0.10.41, and looks like the event emitter API is a bit different.

In particular, [this line](https://github.com/amireh/happypack/blob/master/lib/HappyThread.js#L10) must be rewritten in this way
```
var callbacks = new EventEmitter.EventEmitter();
```

in order to make it work on that node js version.

Do you think would it be possible to handle both cases?

**Comment by amireh** [comment]
Absolutely, I'll push a new version over the weekend. I'll also have node 0.10 on CI to catch any future regressions.

Thanks for reporting!

**Comment by XVincentX** [comment]
That's great! Thanks a lot!

**Comment by amireh** [comment]
Version 1.1.2 should have the fix for this. Please close once you're able to confirm.

**Comment by XVincentX** [comment]
Thanks a lot, I will definitely have a look as soon as possible.

**Comment by XVincentX** [comment]
It works as expected, thanks!
