### ISSUE TITLE
Discussion: Integration with webpack-blocks

### ISSUE THREAD

**Issue by amilajack** [amireh/happypack#107]
I've [started a discussion in the webpack-blocks repo](https://github.com/andywer/webpack-blocks/issues/14) on adding support for happypack. @amireh what do you think about working with me on a PR to add support?

**Comment by fenos** [comment]
is there any progress on this? 👍

**Comment by amilajack** [comment]
Not yet.

**Comment by amireh** [comment]
I think we can close this here since it was closed in https://github.com/andywer/webpack-blocks/issues/14 and an implementation exists in https://github.com/diegohaz/webpack-blocks-happypack
