### ISSUE TITLE
Process.env.NODE_ENV is undefined

### ISSUE THREAD

**Issue by jeffycai** [amireh/happypack#108]
When using happypack,
In the webpack configuration file
     New webpack.DefinePlugin ({
         'Process.env': {
             NODE_ENV: JSON.stringify ('production')
         },
     }),
Process.env.NODE_ENV is undefined, the above settings do not work.

**Comment by jeffycai** [comment]
is error in redux-dom.js

**Comment by amireh** [comment]
I think you got the config correctly. I can safely say that happypack wouldn't affect that since I'm using that plugin in multiple projects with no problem.

Try switching your config block to something like this:

```javascript
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify ('production'),
}),
```

Now your code should be able to use `if (process.env.NODE_ENV === 'production') {}` etc.

**Comment by jeffycai** [comment]
According to the solution you provided, without success, NODE_ENV or undefined

If (process.env.NODE_ENV! == 'production') {
(Function () {
Var printWarning = function printWarning (format) {
_key <_len; _key ++) {var_len = arguments.length, args = Array (_len> 1? _len - 1: 0)
Args [_key - 1] = arguments [_key];
}}

Var argIndex = 0;
Var message = 'Warning:' + format.replace (/% s / g, function () {
Return args [argIndex ++];
});
If (typeof console! == 'undefined') {
Console.error (message);
}}

**Comment by jeffycai** [comment]
HAPPYPACK version related?

**Comment by amireh** [comment]
Shouldn't be. What's your webpack version? And please try a simpler test, like `console.log(process.env.NODE_ENV)`

**Comment by jeffycai** [comment]
ok,thank you very much -_-

**Comment by amireh** [comment]
Is it still not working? Some logs and config could be useful, otherwise please close the issue.
