### ISSUE TITLE
happypack/loader not found

### ISSUE THREAD

**Issue by shrynx** [amireh/happypack#113]
for some webpack isn't able to find 'happypack/loader'. i get this in error logs.
```js
Happy[1]: Loaded 0 entries from cache. (0 were stale)
Happy[1]: All set; signalling webpack to proceed.                                                                                                                               
 Error in multi main                                                                                                                                                         
 Module not found: Error: Cannot resolve module 'happypack/loader'
 module variation happypack-loader
```
Any solutions ? or if someone else facing this issue ?

**Comment by amireh** [comment]
Hmmm, that is really strange. Can you show your webpack config plz?

**Comment by tocjent** [comment]
@shrynx @amireh I had this issue when some of the `require`s were mapped to a different directory with separate `node_modules`. For example:

`app/webpack.config.js`
```
{
  resolve: {
    alias: {
        app2: path.resolve('./../app2/src/'),
    }
  }
}
```

It was fixed by adding `happypack` alias in webpack config:

```
  happypack: path.resolve('./node_modules/happypack'),
```

**Comment by amireh** [comment]
You could also point directly to the loader in your `module` config:

```javascript
module: {
  loaders: [{ loader: path.resolve(__dirname, './node_modules/happypack/loader.js') }]
}
```

That should be cleaner than using an alias for a loader.

**Comment by shrynx** [comment]
Sorry for the silence, I was sick. Probably @tocjent solution will resolve the issue as I have multiple node modules folder (using learna). Will report back soon. 
Thanks.

**Comment by shrynx** [comment]
This works for me. Thanks @tocjent @amireh

**Comment by yfilali** [comment]
Sorry to chime in on a closed issue, but if you are encountering this on an ejected create-react-app (webpack 1), then you most likely still have the resolveLoaders section in your webpack.config js file. Remove it as indicated in the comments and happypack/loader should resolve just fine.

**Comment by skyrpex** [comment]
@amireh @shrynx I know this is old, but it's much better to use `require.resolve('happypack/loader')`. That will return the absolute path to the module 👍

**Comment by s0ber** [comment]
For those who still can't make it work, there is another way to approach this. You need to add `resolveLoader.root` setting with absolute path pointing to `node_modules` folder which contains loaders.

```
resolveLoader: { root: path.join(__dirname, "node_modules") }
```

It is described here in IMPORTANT section:
https://webpack.github.io/docs/configuration.html#module-loaders
