### ISSUE TITLE
image-webpack-loader Error!

### ISSUE THREAD

**Issue by Anehta** [amireh/happypack#114]
`var webpack = require("webpack");
var path = require("path");
var HappyPack = require("happypack")
var happyThreadPool = HappyPack.ThreadPool({ size: 6 });

module.exports = {
    entry: "./src/index.js",
    output: {
        path:'public',
        filename: "bundle.js", 
    },
    // Enable sourcemaps for debugging webpack's output.
    devtool: "sourcemap",
    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: ['', '.webpack.js', '.web.js','.js']
    }, 

    module: {
        loaders: [
            { 
                test: /\.css$/,
                loaders: ['happypack/loader'+'?id=css']
            },
            {
                test:/\.scss$/,
                loaders: ['happypack/loader' + '?id=scss']
            },
            {
                test: /\.less$/,
                loaders: ['happypack/loader' + '?id=less']
            },
            {
                test: /.*\.(gif|png|jpe?g|svg)$/i, 
                loaders: ['happypack/loader' + '?id=img']
            },
            //// All files with a '.ts' or '.tsx' extension will be handled by 'ts-loader'.
            //{
            //    test: /\.tsx?$/, loaders: [
            //      'react-hot',
            //      "ts-loader"
            //    ],
            //    exclude: path.resolve(__dirname, 'node_modules'),
            //    include: path.resolve(__dirname,'src')
            //},
            {
                test: /\.js$/, loaders: [
                    'happypack/loader'+'?id=js'
                ]
            }
        ],

        preLoaders: [
            // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
            { test: /\.js|\.tsx?$/, loader: "source-map-loader" },
            
        ]
    },
    imageWebpackLoader: {
        mozjpeg: {
            quality: 65
        },
        pngquant: {
            quality: "65-90",
            speed: 4
        },
        svgo: {
            plugins: [
              {
                  removeViewBox: false
              },
              {
                  removeEmptyAttrs: false
              }
            ]
        }
    },
    resolve: {
        alias: {
            'jquery-ui/data': 'jquery-ui/ui/data.js',
            'jquery-ui/disable-selection': 'jquery-ui/ui/disable-selection.js',
            'jquery-ui/focusable': 'jquery-ui/ui/focusable.js',
            'jquery-ui/form': 'jquery-ui/ui/form.js',
            'jquery-ui/ie': 'jquery-ui/ui/ie.js',
            'jquery-ui/keycode': 'jquery-ui/ui/keycode.js',
            'jquery-ui/labels': 'jquery-ui/ui/labels.js',
            'jquery-ui/jquery-1-7': 'jquery-ui/ui/jquery-1-7.js',
            'jquery-ui/plugin': 'jquery-ui/ui/plugin.js',
            'jquery-ui/safe-blur': 'jquery-ui/ui/safe-blur.js',
            'jquery-ui/scroll-parent': 'jquery-ui/ui/scroll-parent.js',
            'jquery-ui/tabbable': 'jquery-ui/ui/tabbable.js',
            'jquery-ui/unique-id': 'jquery-ui/ui/unique-id.js',
            'jquery-ui/version': 'jquery-ui/ui/version.js',
            'jquery-ui/widgets/draggable': 'jquery-ui/ui/widgets/draggable.js',
            'jquery-ui/widgets/droppable': 'jquery-ui/ui/widgets/droppable.js',
            'jquery-ui/widgets/resizable': 'jquery-ui/ui/widgets/resizable.js',
            'jquery-ui/safe-active-element': 'jquery-ui/ui/safe-active-element.js',
            'jquery-ui/core': 'jquery-ui/ui/core.js',
            'jquery-ui/widget': 'jquery-ui/ui/widget.js',
            'jquery-ui/widgets/mouse': 'jquery-ui/ui/widgets/mouse.js',
            //'jquery-ui-css': 'jquery-ui/../../themes/base'
        }
    }, 
    plugins: [
        createHappyPlugin('js', ['react-hot','babel-loader']),
        createHappyPlugin('css', ['style!css']),
        createHappyPlugin('scss', ['style!css!sass']),
        createHappyPlugin('less', ['style!css!less']),
        createHappyPlugin('img-hash',['file?hash=sha512&digest=hex&name=[hash].[ext]']),
        createHappyPlugin('img', ['file?hash=sha512&digest=hex&name=[hash].[ext]','image-webpack']),

        new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('../../reactdllpack/mainfest.json'),
            }),
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        }),
          //new webpack.optimize.UglifyJsPlugin({
          //    compress:{
          //        warnings:false,
          //        drop_console:true

          //    },
          //    mangle:{
          //        except:['$super','$','exports','require']
          //    }
          //})
    ],
    
    devServer: {
        contentBase: './public'
    },

    // When importing a module whose path matches one of the following, just
    // assume a corresponding global variable exists and use that instead.
    // This is important because it allows us to avoid bundling all of our
    // dependencies, which allows browsers to cache those libraries between builds.
  
};

function createHappyPlugin(id, loaders) {
    return new HappyPack({
        id: id,
        loaders: loaders,
        threadPool: happyThreadPool,

        // disable happy caching with HAPPY_CACHE=0
        cache: process.env.HAPPY_CACHE === '1',

        // make happy more verbose with HAPPY_VERBOSE=1
        verbose: process.env.HAPPY_VERBOSE === '1',
    });
}
`

Error:
`TypeError: Expected a buffer
    at Function.module.exports.buffer (C:\svnproject\TsxTest\TsxTest\node_modules\imagemin\index.js:58:25)
    at Object.module.exports (C:\svnproject\TsxTest\TsxTest\node_modules\image-webpack-loader\index.js:41:8)
    at applySyncOrAsync (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:341:21)
    at apply (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:268:5)
    at C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:131:7
    at applyPitchLoader (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:184:14)
    at applyPitchLoader (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:192:14)
    at applyPitchLoader (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:192:14)
    at applyPitchLoaders (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:222:4)
    at applyLoaders (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:116:3)
TypeError: Expected a buffer
    at Function.module.exports.buffer (C:\svnproject\TsxTest\TsxTest\node_modules\imagemin\index.js:58:25)
    at Object.module.exports (C:\svnproject\TsxTest\TsxTest\node_modules\image-webpack-loader\index.js:41:8)
    at applySyncOrAsync (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:341:21)
    at apply (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:268:5)
    at C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:131:7
    at applyPitchLoader (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:184:14)
    at applyPitchLoader (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:192:14)
    at applyPitchLoader (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:192:14)
    at applyPitchLoaders (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:222:4)
    at applyLoaders (C:\svnproject\TsxTest\TsxTest\node_modules\happypack\lib\applyLoaders.js:116:3)`

**Comment by amireh** [comment]
One thing that comes to mind is that you're configuring the loader on the root webpack config map. HappyPack won't serialize that option unless you tell it to like this:

```javascript
const HappyPack = require('happypack');

HappyPlugin.SERIALIZABLE_OPTIONS.push('imageWebpackLoader');
```

Try that and see if it helps. If it *does* help, I will make a proper API for adjusting those options.

**Comment by Anehta** [comment]
THANK FOR HELP!

**Comment by chhu1** [comment]
@Anehta 

I am having this issue as well.

```
HappyPack.SERIALIZABLE_OPTIONS.push('imageWebpackLoader');
```

did not help

**Comment by hxlniada** [comment]
@amireh help!!! Having this issue, and 
```
HappyPack.SERIALIZABLE_OPTIONS.push('imageWebpackLoader');
```
did not help

**Comment by fly39244080** [comment]
did you resolve this problem? I have same problem, can you help me? thanks

**Comment by maplecumt** [comment]
I solved this by load images without happypack.

Load images in traditional way.
`
rules: [
      {
        test: /\.js[x]?$/,
        exclude: /node_modules/,
        use: 'happypack/loader?id=jsx',
      },
      {
        test: /\.css$/,
        use: 'happypack/loader?id=cssloader'
      },
      {
        test: /\.less$/,
        use: 'happypack/loader?id=lessloader'
      },
      {
        test: /\.json$/,
        use: "happypack/loader?id=jsonloader"
      },
      {
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg|jpeg)$/,
        use: [
          'url-loader?limit=10000',
          'img-loader'
        ]
      }
`
