### ISSUE TITLE
happypack always prompt Loaded 0 entries from cache

### ISSUE THREAD

**Issue by hawx1993** [amireh/happypack#116]
Happy[1]: Loaded 0 entries from cache. (0 were stale)

why happypack always prompt loaded 0 entries

I have `.happypack` folders in my  project directory

in the `.happypack` folders, there is a file named:'cache--1.json':

```javascript
{"context":{"loaders":[{"path":"/Users/username/projectname/node_modules/babel-loader/lib/index.js","query":"?presets[]=es2015"}],"external":{}},"mtimes":{}}
```

this is my happyPack settings:

>webpack.config.js

```javascript
  var os = require('os'),
  HappyPack = require('happypack'),
  happyThreadPool = HappyPack.ThreadPool({ size: os.cpus().length });

  new HappyPack({
      cache: true,
      threadPool: happyThreadPool,
      loaders: [ 'babel-loader?presets[]=es2015' ]
    })
```
I confused that why always loaded zero entries  rather than  1 entries or 2 entries ，is the cache setting wrong?

**Comment by amireh** [comment]
Hmm, it seems the cache is _empty_ because `mtimes` has no entries in it. It should populate that object as the build is running.

Can you run happypack with the options `{ debug: true, verbose: true }` and see if there's any output in the console that may help us track this?

**Comment by DanielSundberg** [comment]
I also always get: 
````
Happy[1]: Loaded 0 entries from cache. (0 were stale)
````

<code>mtimes</code> is empty here as well. Using <code>{ debug: true, verbose: true }</code> just gives me a few extra lines in the output:

````
> npm run build

> blabla@0.0.1 build C:\Code\blabla
> webpack

Happy[1]: Version: 3.0.3. Using cache? yes. Threads: 3
Happy[1]: Loaded 0 entries from cache. (0 were stale)
HappyThread[1:0] is now open.
HappyThread[1:1] is now open.
HappyThread[1:2] is now open.
Happy[1]: All set; signalling webpack to proceed.

HappyThread[1:0] is now closed.
HappyThread[1:1] is now closed.
HappyThread[1:2] is now closed.
Hash: 7b5aa6a1a4ff2e6b2a17
Version: webpack 1.12.15
Time: 72742ms
````

**Comment by amireh** [comment]
In the light of the change in v4 that [drops caching from happypack](https://github.com/amireh/happypack/blob/master/CHANGELOG.md#400), this ticket is no longer applicable so I'll be closing it. Please feel free to re-open if the issue persists (i.e. it's not related to caching.)
