### ISSUE TITLE
webpack has a trouble?please help me.

### ISSUE THREAD

**Issue by jeffycai** [amireh/happypack#117]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle xx-web-master@0.0.0~prebuild: xx-web-master@0.0.0
6 silly lifecycle xx-web-master@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle xx-web-master@0.0.0~build: xx-web-master@0.0.0
8 verbose lifecycle xx-web-master@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle xx-web-master@0.0.0~build: PATH: C:\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files (x86)\Jenkins\gitdev202\rrtimes\src\web\node_modules\.bin;C:\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\VisualSVN Server\bin;C:\jdk1.7.0_80\BIN;C:\Program Files\TortoiseSVN\bin;C:\apache-maven-3.3.9\bin;C:\PuTTY\;C:\Git\cmd;C:\Git\mingw64\bin;C:\Git\usr\bin;C:\Program Files\TortoiseGit\bin;C:\nodejs\;C:\Users\Administrator\AppData\Roaming\npm
10 verbose lifecycle xx-web-master@0.0.0~build: CWD: C:\Program Files (x86)\Jenkins\gitdev202\rrtimes\src\web
11 silly lifecycle xx-web-master@0.0.0~build: Args: [ '/d /s /c',
11 silly lifecycle   'webpack --colors --display-error-details --config webpack.config.js' ]
12 silly lifecycle xx-web-master@0.0.0~build: Returned: code: 3221225501  signal: null
13 info lifecycle xx-web-master@0.0.0~build: Failed to exec build script
14 verbose stack Error: xx-web-master@0.0.0 build: `webpack --colors --display-error-details --config webpack.config.js`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (C:\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid xx-web-master@0.0.0
16 verbose cwd C:\Program Files (x86)\Jenkins\gitdev202\rrtimes\src\web
17 error Windows_NT 6.1.7600
18 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error xx-web-master@0.0.0 build: `webpack --colors --display-error-details --config webpack.config.js`
22 error Exit status 3221225501
23 error Failed at the xx-web-master@0.0.0 build script 'webpack --colors --display-error-details --config webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the xx-web-master package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --colors --display-error-details --config webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs xx-web-master
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls xx-web-master
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jeffycai** [comment]
@amireh

**Comment by amireh** [comment]
I don't get it. Can you please show your webpack config and specify what exactly is the problem?
