### ISSUE TITLE
Changes in dependencies don't expire the cache

### ISSUE THREAD

**Issue by kmontag** [amireh/happypack#118]
When a loader adds dependencies via `addDependency()`, happypack doesn't expire its cache when those dependencies change.

See https://github.com/kmontag/happypack-dependency-example for a simple working example.

My particular use case is using `sass-loader` with `@import` directives - files aren't recompiled when their imports change.

I've only tested with webpack 2 - I know you're not officially supporting it until the final release, but since that's imminent I figured I'd file the issue now :)

Thanks for this plugin!

**Comment by amireh** [comment]
Up until now this has been working fine since webpack (in v1 at least) is responsible for re-enqueuing all dependencies for transforming when a source changes. I wonder if something has changed in webpack2 regarding this.

**Comment by Memfisrain** [comment]
I've ran into the same problem with less-loader.

My app.less file contains a few @imports, and after changing these imports happypack takes the old version from cache.

webpack version: 2.2.0-rc.3
happypack version: 3.0.1

**Comment by amireh** [comment]
In the light of the change in v4 that [drops caching from happypack](https://github.com/amireh/happypack/blob/master/CHANGELOG.md#400), this ticket is no longer applicable so I'll be closing it. Please feel free to re-open if the issue persists (i.e. it's not related to caching.)

**Comment by kmontag** [comment]
Confirmed it was caching-related, thanks!
