### ISSUE TITLE
Error when ExtractTextPlugin with HappyPack In webPack 1

### ISSUE THREAD

**Issue by Tankpt** [amireh/happypack#121]
## description

Recently, I have add the happyPack to my project to improve the webPack performance. Thanks for the happyPack, It really excellent.

Everything works well (include the babel & css) except the scss Extract from the code. I have write a demo to test this.

test1 : build without happyPack ( npm run build)
test2: build with happyPack (npm run happyPack)

My webPack config 

```
{
 module: {
        loaders: [
          ...
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract("style", "happypack/loader?id=scss")
            }
        ]
    },
    plugins: [
     ...
        createHappyPlugin('scss', ["css", "sass-loader" ]),
    ]
}
```

Error as follow

```
RROR in ./~/.npminstall/normalize.css/5.0.0/normalize.css/normalize.css
    Module parse failed: /Users/tankpt/workspace/extra/node_modules/.npminstall/normalize.css/5.0.0/normalize.css/normalize.css Unexpected token (13:5)

```

And I change my config to 

```
{
 module: {
        loaders: [
        ...
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract("style", "happypack/loader?id=scss")
            }
        ]
    },
    plugins: [
        ...
        createHappyPlugin('scss', ["style", "css", "sass-loader" ]),
    ]
}
```

Error as follow

```
ERROR in ./src/index.scss
Module build failed: ReferenceError: window is not defined
```

## demo

[demo repo](https://github.com/Tankpt/happyPackDemo)

**Comment by amireh** [comment]
Thank you for reporting this. This helped me identify what may be the root issue that's causing all of this trouble with ExtractText, but unfortunately I couldn't figure it out yet.

Will be taking a deep look at this soon.

**Comment by Tankpt** [comment]
Thx for your reply.

**Comment by sayll** [comment]
I have a similar problem, but it appears in webpack2.

**Comment by sresant** [comment]
this should be hopefully fixed with this pr https://github.com/amireh/happypack/pull/125... just need a version update.

**Comment by amireh** [comment]
Is this still a thing with the v4 releases of happypack?

Also there's a misconfiguration I think, you shouldn't be listing the style-loader twice (the second time being in happypack); only once for the `.extract` call is enough:

```javascript
plugins: [
  createHappyPlugin('scss', ["style" /* remove this */, "css", "sass-loader" ]),
  // like:
  createHappyPlugin('scss', ["css-loader", "sass-loader" ]),
]
```

**Comment by amireh** [comment]
closing since this is really old and extract-text has some workarounds that have been mentioned before (and in any case, i'm not gonna fiddle with it)
