### ISSUE TITLE
Now webpack 2 is out of beta status! Could happypack official support for it?

### ISSUE THREAD

**Issue by BlackGanglion** [amireh/happypack#122]
I'm looking forward to，thank you!

**Comment by amireh** [comment]
I've just read the release notes but I still have to study the source code changes.

From what I gathered, [this section](https://webpack.js.org/guides/migrating/#complex-options) regarding "complex options" may not be supported by happypack since we can't distribute cyclic JS objects across processes:

> webpack 1 only support JSON.stringify-able options for loaders. webpack 2 now supports any JS object as loader options.

Other than that, I'll be looking at this over the weekend.

**Comment by phaistonian** [comment]
So? how was your weekend?:)

**Comment by amireh** [comment]
Rather busy actually!! :laughing: 

So it seems that making happypack accept the loader options from the new `options` option as well as `query` makes it work for the babel loader. I hit other issues related to CSS (less-loader and extract-text v2) which I couldn't fix yet. The fact that my main projects are not using webpack2 yet isn't helping so maybe you can help by providing example repositories with broken things.

I can push up an RC with that `options` fix.

**Comment by abergs** [comment]
Looking forward to help beta test this @amireh

**Comment by amireh** [comment]
I'm planning to work with an engineer from [Canvas LMS](https://github.com/instructure/canvas-lms) to get happypack to work with their webpack 2 build today, that should hopefully move this forward and we'll be seeing a PR in the coming few days.

**Comment by abergs** [comment]
Amazing @amireh! We're running webpack + react + typescript and our builds are 2,5 minutes long. It's hurtful. We have about 1200 modules)

**Comment by phaistonian** [comment]
That's nothing ;)

We are at around 2.5k modules, 4.5 minutes (started at about 9 and after tones of tweaks and optimisation we got it at around 4.5).

**Comment by abergs** [comment]
Wow @phaistonian ... That's crippling,

**Comment by amireh** [comment]
So, just as an update, we didn't come across any issue beyond https://github.com/amireh/happypack/commit/05225b58f36bffcc61bcc657badb26320b66b5be to get happypack working with webpack2 in a build that uses babel-loader, handlebars-loader, coffee-loader, and a bunch of home-grown ones specific to Canvas. Hence, no PR mentioned earlier.

I will be making a release soon that incorporates that patch though.

**Comment by phaistonian** [comment]
That's awesome @amireh. 

ETA for the new release ?

**Comment by abergs** [comment]
That's so awesome @amireh!

**Comment by arobbins** [comment]
@amireh Great! Looking forward to the release.

**Comment by amireh** [comment]
Version 3.0.3 can be found now on NPM which incorporates the mentioned change along with another webpack2 related fix so I'll be closing this issue now.

If you guys come across other webpack2 related problems, please report with concrete details.

**Comment by hsz** [comment]
@amireh I have already integrated it with development and production - everything works correct, thank you!

**Comment by phaistonian** [comment]
Thank you @amireh  :)
