### ISSUE TITLE
Cache is not invalidated on .babelrc file changes

### ISSUE THREAD

**Issue by yangit** [amireh/happypack#129]
At least in Webpack2
Which is very sad.

**Comment by amireh** [comment]
Yup but you can instruct HappyPack to learn about that yourself using the [cacheContext](https://github.com/amireh/happypack#cachecontext-object) option. This, of course, assumes the contents of your `.babelrc` are JSON-serializable.

Here's an example:

```javascript
new HappyPack({
  cache: true,
  cacheContext: {
    env: process.env.NODE_ENV,
    babelConfig: require('.babelrc')
  }
})
```

This way, when the contents of `.babelrc` change, `cacheContext` will change and happypack will invalidate its cache.
