### ISSUE TITLE
For react, happypack is not functioning properly

### ISSUE THREAD

**Issue by sayll** [amireh/happypack#132]
for webpack2
```
new HappyPack({
    id          : 'cJSX',
    cache       : true,
    loaders    : [{
      loader: 'babel-loader',
      query : {
        cacheDirectory: true,
        'presets': [
          "es2015",
          'react',
        ],
      }
    }]
  })
```
Unable to run plug in

**Comment by amireh** [comment]
What do you mean? More context please; the error details and the rest of the webpack config.

**Comment by sayll** [comment]
```
│Error in ./app/view/index/index.jsx
│Module parse failed: E:\project\react-webpack\node_modules\happypack\loader.js?id=cJSX!E:\project\react-webpack\app\view\index\index.jsx Unexpected token (6:2)
│You may need an appropriate loader to handle this file type.
│|
│| render(
│|   <h1>test</h1>,
│|   document.getElementById('body')
│| );
└ @ multi webpack-hot-middleware/client?reload=true ./app/view/index/index.jsx 
```
Project [address：https://github.com/sayll/react-webpack](https://github.com/sayll/react-webpack)

happypack :
 [ config_loader ](https://github.com/sayll/react-webpack/blob/master/config/webpack/modules/loader.js)
[config_plugins](https://github.com/sayll/react-webpack/blob/master/config/webpack/modules/plugins.js)


test command： npm run start

**Comment by fenos** [comment]
This is the exactly issue I had when I tried to implement happypack within a `webpack-block` [Here](https://github.com/andywer/webpack-blocks/issues/14#issuecomment-281077086)
We still don't know what can be wrong, my [webpack config](https://gist.github.com/fenos/5e94a31f254a7cf68b7620ec94286aa0)

@amireh any idea? 😄

**Comment by amireh** [comment]
@sayll @fenos thanks for the goodies, they helped me track the issue down. Can you test against the master branch to see if the issue is resolved?!

**Comment by sayll** [comment]
@amireh thanks for you. My problem has been solved.
and And before the variable `let` problem.

**Comment by amireh** [comment]
I'm glad! The change will be found in version 3.0.3 when that is released.

**Comment by amireh** [comment]
Version 3.0.3 can be found now on NPM.
