### ISSUE TITLE
In the end can and wabpack2 combination

### ISSUE THREAD

**Issue by yangchongduo** [amireh/happypack#135]
In the end can and wabpack2 combination

**Comment by amireh** [comment]
Hmm, I'm not sure I understand the question. But if you mean "does happypack now work with webpack2?" then yes.

**Comment by kfeinUI** [comment]
Yep. I just got up and running with the latest HappyPack in a fairly complex configuration.

**Comment by amilajack** [comment]
Should this be closed?
