### ISSUE TITLE
HappyPack always rebuilds, even when successfully loading entries from cache

### ISSUE THREAD

**Issue by astanway** [amireh/happypack#142]
```
Happy[js]: Version: 3.0.2. Using cache? yes. Threads: 8 (shared pool)
Listening at http://0.0.0.0:31337
Happy[js]: Loaded 46 entries from cache. (0 were stale)
Happy[js]: All set; signalling webpack to proceed.
Happy[styles]: Version: 3.0.2. Using cache? yes. Threads: 8 (shared pool)
Happy[styles]: Loaded 1 entries from cache. (0 were stale)
Happy[styles]: All set; signalling webpack to proceed.
webpack building...
webpack built 3ce83139ef18b17407ec in 18008ms
```

When restarting the server from here without making any modifications, the same thing is written out.

Settings:
```
var path = require('path');
var webpack = require('webpack');
var HappyPack = require('happypack');
var happyThreadPool = HappyPack.ThreadPool({ size: 8 });

module.exports = {
    devtool: 'source-map',
    devServer: {
         historyApiFallback: true
     },
    entry: [
      './react/router'
    ],
    output: {
      path: path.join(__dirname, 'dist'),
      filename: 'bundle.js',
      publicPath: '/static/'
    },
  plugins: [
    new webpack.NoErrorsPlugin(),
    new HappyPack({
        cache: true,
        id: 'js',
        loaders: [ 'babel-loader' ],
        threadPool: happyThreadPool
    }),
    new HappyPack({
        cache: true,
        id: 'styles',
        loaders: [ 'style-loader!css-loader!stylus-loader' ],
        threadPool: happyThreadPool
    })
  ],
  module: {
    loaders: [
    // js
    {
      test: /\.js$/,
      loaders: ['happypack/loader?id=js'],
      include: path.join(__dirname, 'react'),
    },
    // CSS
    {
      test: /\.styl$/,
      include: path.join(__dirname, 'react'),
      loaders: ['happypack/loader?id=styles'],
    },
    // file loader, for example- images
    {
      test: /\.(png|jpg|gif|svg)$/,
      loader: 'file-loader'
    }]
  }
};
```

**Comment by amireh** [comment]
I don't see the problem... The cache seems to be in use as the output indicates.

What are you expecting? Keep in mind that even with a populated cache, a "build" will still happen like it normally would with the exception being the application of loaders will be skipped for modules that exist in the cache.

Does that answer it? (FWIW it's strange that your build takes 18s for 46 modules.. try using "eval" instead of "source-map" :)

**Comment by astanway** [comment]
I would expect that if nothing changes, it loads instantly using the previous built version instead of rebuilding. Isn't that the motivation behind happypack?

**Comment by amireh** [comment]
Nope. The caching layer is just a bonus, but what this plugin provides is parallelization.

What you're looking for is provided by the [hard source plugin](https://github.com/mzgoddard/hard-source-webpack-plugin). Like its name implies, it will create a "hard" cache causing webpack on successive builds to skip module compilation altogether.

You can join the two together for the best of both worlds; happypack makes the initial build faster, hard-source makes successive ones nearly instantaneous.

**Comment by astanway** [comment]
Got it, thanks!

**Comment by soliury** [comment]
I also meet the same problem
