### ISSUE TITLE
AssertionError: plugin for the loader '1' could not be found!

### ISSUE THREAD

**Issue by wenkanglin** [amireh/happypack#145]
### repo

https://github.com/wenkanglin/happywebpack-repo

### step

```
> npm install
> npm run dev
```

### issue

When I use `happypack`, it cause error: 
![happypack-error](https://cloud.githubusercontent.com/assets/21100124/24321657/7c9cf8f8-118c-11e7-85f5-d69f7ef1aaa0.png)

I'm a happypack beginner, and I don't know how to fix this issue. Whether anyone here can help me ? :sos:

**Comment by amireh** [comment]
Please include your webpack config, there's likely a mistake there.

**Comment by wenkanglin** [comment]
I close the issue because it has been sloved. Sorry to disturb you. @amireh 
I move the setting of `loader.options` to happypack plugin's `query` option, and the error disappeared.

**Comment by amireh** [comment]
No problem! Glad you figured it out.

**Comment by dsky1990** [comment]
@wenkanglin I have the same problem, i use webpack2 ,can I see you config? thx

**Comment by wenkanglin** [comment]
What's your webpack config about happypack and loaders ? @dsky1990 

This is my webpack config about happypack:
```
const _happyPackConfig = options => ({
  cache: true,
  tempDir: _path.resolve(_dirs.node, '.cache/happypack', options.happyPackCacheName),
  threadPool: _happyPack.ThreadPool({ size: _os.cpus().length })
});
```
```
plugins: [
  new _happyPack(Object.assign(_happyPackConfig(options), {
      id: 'babel',
      loaders: [
        {
          path: 'babel-loader',
          query: { cacheDirectory: true }
        }
      ]
    })),
    new _happyPack(Object.assign(_happyPackConfig(options), {
      id: 'vue',
      loaders: [
        {
          path: 'vue-loader',
          query: Object.assign({ esModule: false }, options.vue)
        }
      ]
    }))
]
```
webpack loaders config related to happypack:
```
module: {
  rules: [
    {
      test: /\.vue$/,
      use: 'happypack/loader?id=vue'
    },
   {
     test: /\.js$/,
     use: 'happypack/loader?id=babel'
   }
  ]
}
```

**Comment by dsky1990** [comment]
@wenkanglin thx, I will try it later

**Comment by xingyun888888** [comment]
@wenkanglin  I use your vue-loader config ,but it cause error,can you help me?

new HappyPack(Object.assign(_happyPackConfig(options), {
                                                 ^
ReferenceError: options is not defined

**Comment by woolson** [comment]
@xingyun888888 you can paste you config here, i just use it with vue-loader, maybe i can supply some help ^-^

**Comment by AndyOGo** [comment]
After I migrated to Webpack 3 I get:
**Module build failed: AssertionError: HappyPack: plugin for the loader 'jsx' could not be found! Did you forget to add it to the plugin list?**
