### ISSUE TITLE
Update readme to reflect webpack 2

### ISSUE THREAD

**Issue by amilajack** [amireh/happypack#146]
The readme says 
> It may, and it may not! Official support for webpack 2 will not land until webpack 2 is out of beta status. Until then, IT wouldn't hurt to try but YMMV.

Should I make a PR to remove this and say that happypack supports webpack 2?

**Comment by amireh** [comment]
Oh yes, I'm just lazy sometimes ☺️

**Comment by welll** [comment]
@amilajack do you wanna do that? If not, let me know and I will create the PR

**Comment by amilajack** [comment]
@welll Would awesome if you could do this. Thanks!
