### ISSUE TITLE
Good or bad idea to check in .happpypack, etc?

### ISSUE THREAD

**Issue by trusktr** [amireh/happypack#150]
Good or bad idea to check in the files that happypack generates, into the project repo?

**Comment by rohan-buchner** [comment]
Bad. I'd consider this in the same vein as a temp, cache, node_modules folder.

**Comment by amireh** [comment]
Yeah I'd second @rohan-buchner - remember that the benefits of happypack don't lie in caching, that's just a cheap bonus we could pull off.

If you're looking into doing this, I would suggest investing the effort into the [hard-source](https://github.com/mzgoddard/hard-source-webpack-plugin) which has such an aggressive impact on (successive) build performance that it may make the effort worthwhile.

You could use both plugins; happypack for faster initial builds, hard-source for successive ones.
