### ISSUE TITLE
`Emitted value instead of an instance of Error` on WARNING under webpack 2.4.1

### ISSUE THREAD

**Issue by sompylasar** [amireh/happypack#161]
happypack 3.0.3
webpack 2.4.1

Likely this happens:
https://github.com/webpack/webpack/blob/e2bb2f41fa9f74f063043249dfc9c06ea6d08c03/lib/NormalModule.js#L113-L115
```js
class NonErrorEmittedError extends WebpackError {
	constructor(error) {
		super();

		this.name = "NonErrorEmittedError";
		this.message = "(Emitted value instead of an instance of Error) " + error;

		Error.captureStackTrace(this, this.constructor);
	}
}

// ...

	createLoaderContext(resolver, options, compilation, fs) {
		const loaderContext = {
			version: 2,
			emitWarning: (warning) => {
				if(!(warning instanceof Error))
					warning = new NonErrorEmittedError(warning);
				this.warnings.push(new ModuleWarning(this, warning));
			},
			emitError: (error) => {
				if(!(error instanceof Error))
					error = new NonErrorEmittedError(error);
				this.errors.push(new ModuleError(this, error));
			},
```

I've printed a stack of where this happens, and it's `happypack`:
```
       at Object.loaderContext.emitWarning (/__CENSORED__/node_modules/webpack/lib/NormalModule.js:112:71)
       at Object.LOADER_RPCS.emitWarning (/__CENSORED__/node_modules/happypack/lib/HappyRPCHandler.js:79:12)
       at HappyRPCHandler.execute (/__CENSORED__/node_modules/happypack/lib/HappyRPCHandler.js:56:22)
       at ChildProcess.acceptMessageFromWorker (/__CENSORED__/node_modules/happypack/lib/HappyThread.js:83:27)
       at emitTwo (events.js:87:13)
       at ChildProcess.emit (events.js:172:7)
       at handleMessage (internal/child_process.js:686:10)
       at Pipe.channel.onread (internal/child_process.js:440:11)
```

Found via `eslint-loader`: https://github.com/MoOx/eslint-loader/issues/172

Related: https://github.com/amireh/happypack/issues/152

**Comment by zinserjan** [comment]
Can you try to install the latest master of happypack from github? #141 was merged but never released.

**Comment by sompylasar** [comment]
@zinserjan Tried to install the latest `amireh/happypack#master`, no observed changes for me, still says `Emitted value instead of an instance of Error`. The https://github.com/amireh/happypack/pull/141 PR does not change the lines that cause the notice.

The string (versus Error object) is coming from the lines shown below, as seen in the stacktrace I provided:
https://github.com/amireh/happypack/blob/665c12e5712b972e8667ca545b4e2ea5e0de6535/lib/HappyRPCHandler.js#L78-L84
```js
LOADER_RPCS = {
  emitWarning: function(loader, payload) {
    loader.emitWarning(payload.message);
  },

  emitError: function(loader, payload) {
    loader.emitError(payload.message);
  },
```

via https://github.com/amireh/happypack/blob/3256a3380dde2e06e3ad2ca3b41e9a81fd4f9673/lib/HappyFakeLoaderContext.js#L42-L47
```js
  loader.emitWarning = function(message) {
    loader._compiler._sendMessage('emitWarning', {
      remoteLoaderId: loader._remoteLoaderId,
      message: message
    });
  };

```

**Comment by waterfoul** [comment]
I've tracked down what's happening. As to how to fix it I have no idea

Basically the message is getting set to some sort of odd object which has no object keys. This eventually gets sent to JSON.serialize by node (Since IPC has to work via strings) which results in the "{}". 

I tried Array.prototype.slice.call but that resulted in an empty array

**Comment by amireh** [comment]
Can you verify that this is fixed in the v4 beta releases? Try `happypack@4.0.0-beta.2`

**Comment by amireh** [comment]
Closing since it should've been fixed in the release mentioned above. Re-open if it isn't!
