### ISSUE TITLE
Add webpack2 like config ?

### ISSUE THREAD

**Issue by hlehmann** [amireh/happypack#162]
in addition of `loaders: [ 'babel?presets[]=es2015' ]`,

could it be possible to set webpack like config:
`use: Array<{loader:string;options:object}>`

**Comment by amireh** [comment]
Hmm, this should already be working. The following sample are all equivalent to happypack:

```javascript
{
  loaders: [
    'babel?foo=1',
    { path: 'babel',   query: 'foo=1' },
    { loader: 'babel', query: 'foo=1' },
    { loader: 'babel', query: '?foo=1' },
    { loader: 'babel', query: { foo: '1' } },
    { loader: 'babel', options: { foo: '1' } },
  ]
```

What's not working for you?

**Comment by amireh** [comment]
Closing since this seems to be a question (the requested notation does work.) Feel free to re-open if you think this is legit but please provide some information if you do.
