### ISSUE TITLE
using ts-loader with happypack

### ISSUE THREAD

**Issue by johnnyreilly** [amireh/happypack#164]
Hey!

We've put some docs and examples in place in ts-loader to guide anyone who wants to use ts-loader with happypack:

https://github.com/typestrong/ts-loader#happypackmode-boolean-defaultfalse

You'd be very welcome to use [our example](https://github.com/TypeStrong/ts-loader/tree/master/examples/happypack) in your repo so there's an example here as well.  Or if you'd like I could submit a PR with it to save you the effort.

Thanks for all your work!

**Comment by amireh** [comment]
Thank you! I'm glad this is finally sorted out. I will be making a wiki article and link to it from the FAQ in the README. :tada:

**Comment by johnnyreilly** [comment]
PR raised!

**Comment by sikaco** [comment]
Very NICE! THX much.
