### ISSUE TITLE
Update the Loader Compatibility List to list ts-loader support

### ISSUE THREAD

**Issue by johnnyreilly** [amireh/happypack#171]
Hey!

Would you be able to update [the wiki](https://github.com/amireh/happypack/wiki/Loader-Compatibility-List) at some point to add ts-loader support please?  

Thanks! ❤️

**Comment by liqiang372** [comment]
I'm not sure if happypack fully supports `ts-loader` since I got following errors trying to do that

```bash
Module build failed: TypeError: loader._compiler.plugin is not a function
TypeError: Cannot read property 'meta' of undefined
```

**Comment by johnnyreilly** [comment]
Hi @liqiang372, that sounds like you're not running in happypackmode (see docs) or with an older version of ts-loader that didn't support it

**Comment by liqiang372** [comment]
@johnnyreilly wow, many thanks, just noticed ts-loader@2.1.0 starts to support happypack 21 days ago, but `npm install ts-loader` still installs 2.0.3 by default.  You saved my night!

**Comment by johnnyreilly** [comment]
No problem!

**Comment by amireh** [comment]
Updated, thanks!
