### ISSUE TITLE
webpack 3 compatible?

### ISSUE THREAD

**Issue by johnnyreilly** [amireh/happypack#172]
Hello again!

I was just wondering if the breaking changes listed against webpack 3 are likely to affect happypack compatibility?

https://github.com/webpack/webpack/releases/

**Comment by amireh** [comment]
Yeah, I just [updated master](https://github.com/amireh/happypack/commit/6dac2705b76f4d7945d8505976e6594689825350) so that the test suite runs against webpack 1, webpack 2, and webpack 3.

You can view the travis job: https://travis-ci.org/amireh/happypack/jobs/253667172

:tada:

**Comment by johnnyreilly** [comment]
Nice!
