### ISSUE TITLE
compilerId not documented

### ISSUE THREAD

**Issue by donaldpipowitch** [amireh/happypack#175]
Just saw the `compilerId` option in the [multi-build](https://github.com/amireh/happypack/blob/master/examples/multi-build/webpack.config.js) example. AFAIK it is not documented.

I think the multi-build example could need some documentation, too. Do I need unique `id`'s _and_/_or_ `compilerId`'s across the multiple configs? Or do they only need to be unique inside _one_ config of the config array?

**Comment by amireh** [comment]
Yeah, we should be documenting that. As to your question, `compilerId` can be considered parallel to `id` - they're not related. `compilerId` can't clash with another `compilerId` value of another plugin, just like `id` can't clash with another `id` value of another plugin.

When either is omitted, the implementation substitutes a default for those values (`1` for `id` and `default` for `compilerId` IIRC) to address the most common case where people have only a single plugin instance and then they don't need to specify (or know about) those things.

Does that help?

**Comment by donaldpipowitch** [comment]
Thank you. Can you give me an example _when_ this should be used?

**Comment by amireh** [comment]
When you're using multiple builds / multiple webpack compilers. See https://github.com/amireh/happypack/pull/97 and the referenced tickets

**Comment by donaldpipowitch** [comment]
Thx.
