### ISSUE TITLE
Why is HappyFSCache gone?

### ISSUE THREAD

**Issue by mvonkeil-ecentral** [amireh/happypack#178]
In the most recent version of happypack there is no more file system caching and HappyFSCache.js seems to be gone. Maybe I'm missing something here, but what's the point of caching without storing the cached data somewhere? 

Could you please explain why this change was made?

**Comment by amireh** [comment]
> Maybe I'm missing something here, but what's the point of caching without storing the cached data somewhere?

There'd be no point but since we're not caching anything anymore, there's nothing to store.

I've already responded to this in https://github.com/amireh/happypack/issues/154#issuecomment-305627697

**Comment by mvonkeil-ecentral** [comment]
Ah, exactly what I was looking for. Thank you very much for the fast reply!
