### ISSUE TITLE
babel-loader?cacheDirectory causing issues with webpack-dev-middleware

### ISSUE THREAD

**Issue by dmmulroy** [amireh/happypack#179]
Happypack does not seem to be able to properly locate/transpile using my `.babelrc` if I create a plugin using:
```javascript
//code excluded for brevity
new HappyPack({ 
  id: 'js',
  loaders: ['babel-loader?cacheDirectory']
  threadPool: HappyPack.ThreadPool({ size: 5 }),
  cache: true,
  verbose: true
});
```

When I switch `loaders: ['babel-loader?cacheDirectory']` to `loaders: ['babel-loader']` everything works as normal.  If I build with webpack w/o webpack-dev-middleware everything works fine as well.  In addition, using `babel-loader?cacheDirectory` directly as a loader without happypack works as well.

**Comment by magestican** [comment]
This is my config and works fine : 
```
new HappyPack({
    loaders: [ 'babel?cacheDirectory=true' ]
    }),
```

And on the loaders 
```
{
        test: /\.js$/,
        include: path.join(__dirname, 'src'),
        use: [
          {
            loader: 'happypack/loader',
          }
        ]
      }
```

**Comment by amireh** [comment]
It could be something to do with the context directory; can you try assigning `{ context: path.resolve(__dirname) }` in your webpack.config.js ?

**Comment by amireh** [comment]
as @magestican says, I just tried it to confirm and it seems to be working ok. Make sure you're passing either `true` or a path to the cache directory as a value (in your example you seem to pass no value at all..)
