### ISSUE TITLE
Can't use tslint-loader: TypeError: this.addDependency is not a function

### ISSUE THREAD

**Issue by Strate** [amireh/happypack#18]
Trying to use [tslint-loader](https://github.com/wbuchwalter/tslint-loader), happypack fails with `TypeError: this.addDependency is not a function`

**Comment by Strate** [comment]
Oh, sorry, this feature seems not merged yet (#15)

**Comment by amireh** [comment]
Looking into it, need to figure out the deal with preLoaders / postLoaders. Any sample configs / sources would help a lot!
