### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by geyanku** [amireh/happypack#194]
Use happyPack + vue-loader and get this warning: 
![image](https://user-images.githubusercontent.com/6949015/31593910-2b43fd92-b1f7-11e7-8dad-bfcb2f203bee.png)

Here's my webpack config:
```
const HappyPack = require('happypack')  
const os = require('os')  
const happyThreadPool = HappyPack.ThreadPool({ size: os.cpus().length })  
...  
module: {  
    rules: [  
    {  
        test: /\.vue$/,  
        loader: 'happypack/loader?id=vue',  
    },  
 ...  
plugins: [  
    new HappyPack({  
      id: 'vue',  
      threadPool: happyThreadPool,  
      cache: true,  
      verbose: true,  
      loaders: [{  
        loader: 'vue-loader',  
        options: vueLoaderConfig  
      }]  
    }),  
...  
```
thanks for help

**Comment by Richar-Dada** [comment]
I meet this problem too

**Comment by amireh** [comment]
Can you show me what's inside `vueLoaderConfig`?

**Comment by geyanku** [comment]
Here's my  vueLoaderConfig
@amireh 
```
var utils = require('./utils')
var config = require('../config')
var isProduction = process.env.NODE_ENV === 'production'

module.exports = {
  loaders: utils.cssLoaders({
    sourceMap: isProduction
      ? config.build.productionSourceMap
      : config.dev.cssSourceMap,
    extract: isProduction
  }),
  transformToRequire: {
    video: 'src',
    source: 'src',
    img: 'src',
    image: 'xlink:href'
  },
  postcss: [require('postcss-cssnext')()]
}
```

**Comment by amireh** [comment]
`postcss: [require('postcss-cssnext')()]` won't work as stated in many other issues (mostly related to postcss.)

Functions can't be serialized by happypack; your webpack configuration has to be free of functions in any loader configuration. To fix this particular problem, postcss [accepts configuration from a file](https://github.com/postcss/postcss-loader#config). So pass it a _path_ to a file that has `module.exports = [ require('postcss-cssnext')() ]` and it should be OK.

I hope that helps.

**Comment by geyanku** [comment]
It works! Thanks for help @amireh
