### ISSUE TITLE
Happypack@4.0.0-beta.5 throws when used with react-hot-loader@3.1.1 

### ISSUE THREAD

**Issue by trustmore** [amireh/happypack#195]
Webpack@v3.7.1
Happypack@v4.0.0-beta.5
react-hot-loader@3.1.1 

`new HappyPack({
    id: 'jsx',
    loaders: ['react-hot-loader', 'babel-loader?cacheDirectory']
})`

error:
`ERROR in ./app/index.js
Module build failed: TypeError: fn.apply is not a function
    at applySyncOrAsync (/Users/chengang/projects/ifusion/node_modules/happypack/lib/applyLoaders.js:350:21)
    at apply (/Users/chengang/projects/ifusion/node_modules/happypack/lib/applyLoaders.js:277:5)
    at /Users/chengang/projects/ifusion/node_modules/happypack/lib/applyLoaders.js:283:9
    at /Users/chengang/projects/ifusion/node_modules/babel-loader/lib/index.js:171:14
    at /Users/chengang/projects/ifusion/node_modules/babel-loader/lib/fs-cache.js:113:24
    at /Users/chengang/projects/ifusion/node_modules/babel-loader/lib/fs-cache.js:44:14
    at Gunzip.onEnd (zlib.js:213:5)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
 @ multi webpack-dev-server/client?http://localhost:8470 webpack/hot/dev-server ./app/index.js`

**Comment by amireh** [comment]
Please share your webpack config

**Comment by caylor** [comment]
because what react-hot-loader exports is not a function

react-hot-loader@3.1.1
`module.exports.AppContainer = AppContainer;`

just use 'react-hot-loader' with a lower version OR use 'react-hot-loader/webpack'

**Comment by sibelius** [comment]
I think we can close this
