### ISSUE TITLE
options validator still supports loaders.path, but is it really still valid?

### ISSUE THREAD

**Issue by jedwards1211** [amireh/happypack#199]
I noticed that https://github.com/amireh/happypack/blob/master/lib/HappyPlugin.js#L54 still allows
```js
new HappyPlugin({
  loaders: [{
    path: 'babel-loader',
  }]
})
```
But it seems like my files don't get babelified unless I change that to `loader: 'babel-loader'`.  I'm guessing that support for `path` was dropped but someone forgot to update the options validator accordingly.  Amirite?

**Comment by jedwards1211** [comment]
I'd recommend using flow and [`flow-runtime`](https://github.com/codemix/flow-runtime) to validate the options.

**Comment by amireh** [comment]
I'm fairly confident this has not changed as it would have been a pretty breaking change. The [code](https://github.com/amireh/happypack/blob/master/lib/WebpackUtils.js#L8) hasn't changed, and if such a change did go through, most of our projects would break.

Please verify things are OK on your end, if you're still having issues, paste the full config file and log output.

**Comment by amireh** [comment]
Closing this since there hasn't been any activity, feel free to open another ticket if you're still seeing the problem. Thanks!
