### ISSUE TITLE
Absolute paths in cache

### ISSUE THREAD

**Issue by amasad** [amireh/happypack#201]
When deploying to, say heroku, you'll get a different temporary path on every deploy. And although you can carry over the .happypack cache we won't be able to use it because the paths are absolute. 

Would you be open to changing that to make it relative to the root?

**Comment by amireh** [comment]
Caching has been removed in v4 so this issue isn't applicable anymore. Is there a reason you can't use the latest version?

**Comment by amasad** [comment]
I think v4 is in beta? Also caching was removed? Why? That's the major reason we use happy pack, concurrency is nice to have for initial cold cache builds but that doesn't happen often

**Comment by amireh** [comment]
v4 is out of beta since 8ef785245159bcefa9e394ee5eddc0e584796933 (about 3 months ago.)

Re caching, see https://github.com/amireh/happypack/issues/154#issuecomment-305627697.
