### ISSUE TITLE
Is this the correct behaviour for rebuilds? HappyPack doesn't appear to be working for them.

### ISSUE THREAD

**Issue by benstaker** [amireh/happypack#206]
**Env:** Windows 10 64-bit (latest), **Node:** v6.12.2, **NPM:** v3.10.10, **HappyPack:** v4.0.1

HappyPack only seems to be working for the initial build (lots of node.exe processes), as you can see below:
![initial-build](https://user-images.githubusercontent.com/2591500/35288387-717e18e8-005c-11e8-8371-1567755320fa.png)

However when I change a file it doesn't do what I expected, which is to keep the existing processes open on standby, only a few node processes exist. You can see this below:
![rebuild](https://user-images.githubusercontent.com/2591500/35288394-76023b6a-005c-11e8-9698-035c9a49fc99.png)

I'm not sure whether this intentional behaviour, as I couldn't find anything in the README.md. Could this be a Windows-specific issue?

**Comment by amireh** [comment]
This is intentional, as per the [README](https://github.com/amireh/happypack#threads-number):

> Keep in mind that this is only relevant when performing the initial build as HappyPack will switch into a synchronous mode afterwards (i.e. in watch mode.)

The plugin is concerned with the initial build, afterwards it tries to mimic the original webpack behaviour (because otherwise performance regresses with all the workers for few files.)

**Comment by benstaker** [comment]
@amireh Thank you, my bad. That makes sense.
________________________________
