### ISSUE TITLE
AssertionError [ERR_ASSERTION]: HappyPack: Unrecognized option 'use'

### ISSUE THREAD

**Issue by inoyakaigor** [amireh/happypack#225]
node@9.8.0
webpack@4.5.0
happypack@5β3

I've got an error _AssertionError [ERR_ASSERTION]: HappyPack: Unrecognized option 'use'_
at _/Users/inoy/projects/Statistics/node_modules/happypack/lib/OptionParser.js:32:5_
https://github.com/amireh/happypack/blob/e4e13423754ea5b8c9899214848d1462d42d13f1/lib/OptionParser.js#L33

The problem is in variable _schema.loaders.alias_. This should be "use" not "rules"

UPD:
After manual assigning this variable to "use" i've got other error:

_TypeError: Cannot read property 'reduce' of undefined
at resolveLoaders (/Users/inoy/projects/Statistics/node_modules/happypack/lib/HappyPlugin.js:131:39)_

This error throws because string
https://github.com/amireh/happypack/blob/e4e13423754ea5b8c9899214848d1462d42d13f1/lib/HappyPlugin.js#L130

should be _that.config.use_

**Comment by amireh** [comment]
Oops, I thought I had fixed that. Will amend in 5.0.0-beta.4 - thanks for reporting!
