### ISSUE TITLE
Changelog and list breaking changes

### ISSUE THREAD

**Issue by rpellerin** [amireh/happypack#229]
Hi,
Version 5.0.0 does not introduce any breaking change?
If it does, it would be great if that could be reflected in the `CHANGELOG.md` file.
Thanks!

**Comment by amireh** [comment]
Hello! The changes in 5.0.0 are simply those of the `5.0.0-beta.*` versions. The only potentially breaking change (which caused the major bump) is the minimum node version required now.

I assume we can write that explicitly, PRs welcome.

**Comment by rpellerin** [comment]
Thanks!
