### ISSUE TITLE
[AssertionError [ERR_ASSERTION]]:HappyPack: plugin for the loader '1' could not be found! Did you forget to add it to the plugin list?

### ISSUE THREAD

**Issue by Fiv5** [amireh/happypack#238]
webpack version : v4.12.0
happypack version : v5.0.0
this is my webpack config : 
```js
// module
 module: {
    rules: [
...,
      {
        test: /\.js$/,
        include: path.resolve(__dirname, 'src'),
        exclude: /node_modules/,
        use: {
          loader: 'happypack/loader?id=babel',
          options: {
            // 缓存
            cacheDirectory: true,
          },
        },
      },
...}
```

```js
//plugins:
   new HappyPack({
      // 基础参数设置
      id: 'babel', // 上面loader?后面指定的id
      // loaders: ['babel-loader?cacheDirectory'], // 实际匹配处理的loader
      loaders: [
        {
          path: 'babel-loader',
          query: {
            babelrc: true,
            cacheDirectory: true,
          },
        },
      ], // 实际匹配处理的loader
      threadPool: happyThreadPool,
      // cache: true // 已被弃用
    }),
```

**Comment by FEYeh** [comment]
have same questions

**Comment by xcondor** [comment]
Which webpack version supported happypack？ I used webpack 3.6.0,  the same to above question.

**Comment by yannickguillemot** [comment]
Same here. Any updates on this?

**Comment by amireh** [comment]
The `options` you define inside the `module.rules` is overriding the query string (`?id=babel`) so HappyPack is looking for the default loader (named "1").

You're already configuring the babel loader properly (inside the happy plugin instance) so just omit the `options` from the `module.rules` entry.

Relevant snippets:

```javascript
plugins: [
  new HappyPack({
    id: 'babel',
    loaders: [{
      path: 'babel-loader',
      query: {
        // 缓存
        cacheDirectory: true,
      },
    }]
  })
],

module: {
  rules: [
    {
      test: /\.js$/,
      use: 'happypack/loader?id=babel'
    }
  ]
}
```

**Comment by hanwenbo** [comment]
This bug is too serious to use，I'm going to report that error using any loader.

**Comment by RickyLL** [comment]
> The `options` defined inside the `module.rules` is overriding the query string (`?id=babel`) so happypack's loader is looking for the default plugin instance (named "1"). Can't have both at the same time.
> 
> You're already configuring the babel loader properly (inside the happy plugin instance) so just omit the `options` from the `module.rules` entry.
> 
> Relevant snippets:
> 
> ```js
> module: {
>   rules: [
>     {
>       test: /\.js$/,
>       use: 'happypack/loader?id=babel',
>       // don't put options here, or put options with { id: 'babel' }
>     }
>   ]
> }
> ```
Your offered solution can not fix this problem

**Comment by romanlex** [comment]
Same here. Any updates on this?

**Comment by amireh** [comment]
How does it not fix the problem? What do you see after amending the options? Please see my response [for this similar thread](https://github.com/amireh/happypack/issues/183#issuecomment-467476421).

We've been using multiple loaders since v1 of this plugin and the tests do cover this use case.

**Comment by Zwe1** [comment]
@amireh it helps a lot, i fix it

**Comment by chenyijie-bit** [comment]
If the plugin only supports webpack4 and above and the above solution still does not solve the problem is the use of webpack3 version
