### ISSUE TITLE
SourceMap support

### ISSUE THREAD

**Issue by amireh** [amireh/happypack#28]
TODO:

- [x] figure out what sourcemaps actually look like between loaders (seem to be objects, but the end result might be stringified)
- [x] serialize source-maps (we serialize them as JSON in case they're objects, otherwise we assume they're strings and write them down normally)
- [x] cache source-maps

**Comment by amireh** [comment]
Can you guys try out #36 and provide some feedback?

I've tested with `babel-loader` and `devtool: 'source-map'` and the `.js.map` file that gets generated is identical between raw webpack and the happy webpack versions, but I do not personally use source-maps so I'm not sure what else there is to test.

**Comment by hanjukim** [comment]
Ok I will try

**Comment by hanjukim** [comment]
I tried #36 with `devtool: 'inline-source-map'` in webpack.conf. The result did not change, source-map is there but it's babel transpiled, not original ES6 source.

Without happypack ![without happypack](http://i.imgur.com/uHXcPfp.png)

With happypack ![with happypack](http://imgur.com/heSaWCM.png)

**Comment by amireh** [comment]
@hanjukim I've just tried it again with a sample React app (and ES6 modules like you've screenshotted) and the source map seems to work fine using both `source-map` and `inline-source-map` as `devtool` values.

Is there any chance you haven't cleared happypack's cache? (try `rm -r .happypack/` to do that)

**Comment by hanjukim** [comment]
@amireh Oh my bad. Cache might be a problem. I will try again.

**Comment by hanjukim** [comment]
@amireh After deleting .happypack cache directory, it is working!! I really appreciate your work.

**Comment by amireh** [comment]
Great! I have just published 2.1.0 which should contain SourceMap support. Feel free to open a ticket if you find any weirdness around it, but hopefully there'd be none of that.
