### ISSUE TITLE
happypack makes karma do not generate coverage report 

### ISSUE THREAD

**Issue by geekchow** [amireh/happypack#31]
happypack makes  'karma-coverage' ,do not generate coverage report.

**Comment by amireh** [comment]
How are you generating coverage?

I'm successfully able to use happypack + istanbul instrumentor.  I just use istanbul as a `postLoader` and happypack as the primary loader (with babel etc)

Can you share your configs please

**Comment by geekchow** [comment]
i use webpack + isparta to do code coverage reporting.
the config is 
`
    webpack: {
      module: {
        preLoaders: [
          {
            test: /\.js$/,
            loader: 'babel',
            query: {
              presets: ['es2015'],
            },
          },
          {
            test: /^(.(?!\.spec))*\.js$/,
            loader: 'isparta',
          },
        ],
      },
    },
`
when i use the istanbul to do code reporting, the coverage report result is not the same, the number is slightly diff

**Comment by amireh** [comment]
The numbers are off might be an issue related to babel's transpilation, I remember coming across this issue before.

Can you try using isparta as a `postLoader` instead? I believe you should run babel _before_ isparta (and try the `retainLines: true` option for babel see if it helps with the reporting...)

**Comment by amireh** [comment]
Closing this as there's no context provided.

FWIW, we've been having no issues with karma + webpack + istanbul + happypack so it's likely a configuration issue.
