### ISSUE TITLE
Smarter cache detection?

### ISSUE THREAD

**Issue by XVincentX** [amireh/happypack#35]
Actually, cache stale detection is done using `mtime` field, which works pretty well.
I was considering whether it might have sense to use a clever mechanism, such as hashing the file content.

The main reason for that is, basically, *CI* environment re-download sources every time, so the cache would be stale by default (which is not really true)

**Comment by amireh** [comment]
We can do that, but I'm curious, how would you have a populated cache in a CI environment? Won't the build be triggered just that one time?

**Comment by XVincentX** [comment]
Unfortunately I have fronted and backend in the same repo. So, when I push a lot of backend stuff, I want to use the cache to speed up my build, as it is not changing at all.

**Comment by amireh** [comment]
Sure, what I'm thinking is to expose a config parameter that allows you to generate a signature for each file and HappyPack will use those signatures to figure out if a file is stale. The default signature generator would be the existing mtime statter, and then you can define your own hashing technique or whatever works for you.

Something like:

```javascript
HappyPack({
  fileSignatureGenerator: function(filePath) {
    return computeDigest(fs.readFileSync(filePath, 'utf-8'));
  }
});
```

How about that?

**Comment by XVincentX** [comment]
That would fit perfectly my need! I can eventually work on that!

**Comment by amireh** [comment]
Great, let me work it out then

**Comment by amireh** [comment]
Check out `2.0.6` and pass in your signature generator as `cacheSignatureGenerator`. Let me know how it goes!

**Comment by XVincentX** [comment]
Hey man...you're too fast!

**Comment by XVincentX** [comment]
@amireh It throws if that parameter is passed as undefined (expected behaviour would be revert to default function). But it's manageable.

**Comment by amireh** [comment]
Hmm, that shouldn't happen. Can you share the trace and the config?

**Comment by XVincentX** [comment]
I think the problem is the validation on [this line](https://github.com/amireh/happypack/commit/37a8b54045588a9dd5e4efa1f63d8fbd30d794e5#diff-51efeac99eefce928437af1e35e0dec6R40)
