### ISSUE TITLE
Trying to use the `extract-loader` for scss, getting a `_this2.loadModule` error.

### ISSUE THREAD

**Issue by piggyslasher** [amireh/happypack#39]
The plugin structure is like so:
```
new HappyPack({
      id: 'scss',
      // loaders: ['style!extract!css!resolve-url!sass'],
      loaders: ['file?name=bundle.css!css!resolve-url!sass'],
      threads: 2,
      cache: true,
    }),
```

Error:
```
ERROR in ./src/content/stylesheets/index.scss
Module build failed: Error: _this2.loadModule is not a function
```

**Comment by amireh** [comment]
Yeah it seems this is a missing API in the fake loader context. I'll have to see what it does to see if we can shim it.

Is "extract" something similar to the `ExtractTextPlugin`? Because we know that can't be used that like.

**Comment by amireh** [comment]
This should work as of 2.2.0 since `this.loadModule()` support has been added, closing.
