### ISSUE TITLE
React hot module replacement doesn’t when using Happypack

### ISSUE THREAD

**Issue by crvst** [amireh/happypack#43]
Hello there, Happypack breaks somehow Webpack HMR when updating React components like this:
```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves.
```
Does anybody know how to make things working well when using both Happypack and Webpack’s HMR? Or what could go wrong?

**Comment by amireh** [comment]
Are you using [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware) or something else? Can you share some configs please?

**Comment by crvst** [comment]
Excuse me for loooong delay. I’m using [react-hot-loader](https://github.com/gaearon/react-hot-loader).

**Comment by amireh** [comment]
Did you figure this out? It's likely a configuration issue which is hard to help you with if you won't provide the config.

I have recently had to use happypack with a project that uses HMR (with `react-hot-loader` + `webpack-hot-middleware`) and it's been working just fine.

**Comment by todd-richmond** [comment]
I'm also able to use react hot loader 1 (GA version, not beta) with happypack. Need to include 'react-hot' in the jsx loader list and 'webpack/hot/only-dev-server' and 'webpack-hot-middleware/client' at the beginning of the entry list

I also use 'react-hmre' in the babelrc development presets

**Comment by amireh** [comment]
Thanks for reporting @todd-richmond.

I'm gonna close this since it doesn't look like an issue, but feel free to re-open if you find out otherwise.

**Comment by sibelius** [comment]
@todd-richmond can you share your webpack config?

or what solved your problem?
