### ISSUE TITLE
Error listen EADDRINUSE if run with --debug flag

### ISSUE THREAD

**Issue by albertogasparin** [amireh/happypack#47]
I'm using webpack-dev-middleware and webpack-hot-middleware, so I can start webpack dev server directly from my main app.
However, if I run node with the `--debug` flag, it looks like it gets propagated to the child processes that Happy creates. As a result, with 3 threads I get 3 times EADDRINUSE error on the console.

Removing the flag makes Happy happy again 😄 (and my build times are 60% faster!!)
Is there a way to say to Happy to ignore the debug flag?

**Comment by amireh** [comment]
> Removing the flag makes Happy happy again

Lol!

So let me get this straight, is it passing the `--debug` argument down to the child processes so then they end up running in debug mode or is this an environment variable (because the env is shared when we `fork`)?

**Comment by albertogasparin** [comment]
`--debug` argument.
I've reproduced the issue [in this repo branch](https://github.com/albertogasparin/react-starterkit/tree/webpack-perf). After installing the dependencies, you can see the error by running `node --debug ./server.js`.
If I try without the server (e.g. `npm run build`) webpack compiles correctly with Happy enabled.

**Comment by i8ramin** [comment]
+1

**Comment by amireh** [comment]
Thanks for reporting and making that test repo - it makes it so much easier!

The fix should land in the next release, I'll update the ticket when that happens.
