### ISSUE TITLE
Unable to cache between machines.

### ISSUE THREAD

**Issue by gdborton** [amireh/happypack#50]
We're currently investigating using happypack to cache our ci builds between different commits.  Our basic setup is to download a happypack cache (if one exists), clone, run webpack, upload happypack cache.

We've hit two issues with this.  The first is that modified-time isn't preserved by git (we worked around this by changing the signature function to be a hash of the file content).  The second issue that we're hitting is that the happypack cache uses absolute file paths, which aren't consistent between builds.

I would like to propose changing the structure of the cache to enable cached builds across machines and clones...

From:
```javascript
{
  '/path/to/files.js': {
    mtime: '2016-05-25 25:12:12', // pretend this is a real time stamp
    compiledPath: '/path/.happypack/s--1411414904'
  },
},
```

To:
```javascript
{
  // sha-256 based on file content.
  'fa9a499ca3f660206bec74fb7ed3603174c17c2f3846a9968a3caf8e995b791b': {
    compiledPath: '.happpack/s--1411414904' // config.tempDir + cache file name.
  }
}
```

I'd be happy to work on this, but I wanted to get your opinion first.

**Comment by amireh** [comment]
Hmm, but how would we be able to know when a cache entry becomes stale if we're hashing by content?

I would rather stay away from calculating digests if it can be avoided.

> The second issue that we're hitting is that the happypack cache uses absolute file paths, which aren't consistent between builds.

How about we address this directly? We can define an option for specifying the root directory (a _common prefix_ if you will) that the cache would omit when its tracking file paths. This way, compiling `lib/a.js` from either `/tmp/lib/a.js` or `/home/foo/project/lib/a.js` would still yield `lib/a.js`.

A value to such an option can normally be `process.resolve(__dirname)` if `webpack.config.js` is in the root directory of the project.

The only downside to this approach I can see is that it will not work for sources _outside_ of the repository, but I think that's an edge case we can safely ignore.

What do you think about this?

**Comment by gdborton** [comment]
> Hmm, but how would we be able to know when a cache entry becomes stale if we're hashing by content?
Do you mean if we key on the hash, how do we know when a file is unused and should be removed from the cache?

> We can define an option for specifying the root directory (a common prefix if you will) that the cache would omit when its tracking file paths. This way, compiling lib/a.js from either /tmp/lib/a.js or /home/foo/project/lib/a.js would still yield lib/a.js.

This would work for building in different directories, but we'd still have to address modified-time not being preserved across clones.

**Comment by amireh** [comment]
> Do you mean if we key on the hash, how do we know when a file is unused and should be removed from the cache?

Yes, since file paths are "static" identifiers for files, whereas digests are not.

> This would work for building in different directories, but we'd still have to address modified-time not being preserved across clones.

Sniffing the modified-time stamp is enough for most cases that's why it's the default, but we've provided the option to generate your own signature for this very reason. See #35 for more context around why this was introduced; I think it was the exact same scenario. Is it not working properly?

**Comment by gdborton** [comment]
Regarding the stale cache, we would run into a similar issue by keying on file name when files are moved right?

Generating our own signature is working, I just thought an approach like this would kill two birds with one stone.

**Comment by amireh** [comment]
> Regarding the stale cache, we would run into a similar issue by keying on file name when files are moved right?

You're absolutely right. I didn't really think much about this as there was little harm in the cache not being "pruned". 

It certainly seems more convenient to use digests as keys in your case. Perhaps we can introduce a `cacheKeyGenerator` options that goes along with `cacheSignatureGenerator` giving you the handles to do whatever you want here. In the default case, it would be the identity function.

What do you think about that?

**Comment by gdborton** [comment]
Relative file paths may be preferable in this case.  It accomplishes the same thing with less api surface area, but either would work for our use case.

In the meantime we're running a script before webpack to replace the project directories in each of the `cache--${id}.json` files.

**Comment by gdborton** [comment]
A prune option could be nice though to remove any cache entries/files that are no longer used for the build.  Keeping a list of any entries that are used during a compile, then removing anything keys that aren't in that list.

**Comment by amireh** [comment]
Just to clear things here so that we go forward, the course of action is to:

1. use relative file paths as cache keys
2. create a prune API and run it implicitly on plugin startup (if a cache was found)

Does that sound right? Or would you still prefer to have an API for defining the keys?

**Comment by gdborton** [comment]
That looks good to me.

**Comment by amireh** [comment]
Would you be up to making a PR for this?

**Comment by gdborton** [comment]
Sure, I could get a PR out.

**Comment by amireh** [comment]
On second thought, I don't want to make this change. It's simple and functional as it is, and since it's very easy to work around in scripting (which you're probably already doing to clone the cache), it's not worth complicating the APIs.

Regarding pruning, happypack is already doing it, I'm not sure why I said it wasn't. :grin:
