### ISSUE TITLE
Node_env=production doesn't work with babelrc env.plugins

### ISSUE THREAD

**Issue by freddi301** [amireh/happypack#57]
Babel doesn't pick up the babel_env for conditional pligins

**Comment by amireh** [comment]
Please care to provide some additional context; webpack config, .babelrc, expected behavior, etc.

**Comment by freddi301** [comment]
Nevermind, Webpack changed behaviour about passing envirnment variables.
The only way it works is to specify NODE_ENV=production from npm script or broader context

**Comment by jedwards1211** [comment]
@amireh does happypack spawn its extra processes with the same environment variables as the parent process?  I'm seeing some files get compiled with coverage and some not.  My happypack plugin config looks like this:

```js
    new HappyPack({
      loaders: [{
        path: 'babel-loader',
        options: {
          "presets": [["es2015", {loose: true, modules: false}], "stage-1", "react", "flow"],
          "plugins": [
            "transform-runtime",
            "react-hot-loader/babel",
          ],
          "env": {
            "coverage": {
              "plugins": [
                "istanbul"
              ]
            }
          }
        }
      }],
      threads: 4,
```

So if happypack isn't passing `BABEL_ENV` to its child processes, that would be why some of my files aren't getting compiled with `babel-plugin-istanbul`.

**Comment by jedwards1211** [comment]
@amireh nope, I logged `process.env.BABEL_ENV` in `HappyWorkerChannel.js` and it was getting passed through.  Maybe there's something weird going on in `babel-loader` itself?

**Comment by amireh** [comment]
We're using the default options for ChildProcess#fork which is similar to [ChildProcess#spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) and they pass on `process.env` as it is to the child processes, so your environment variables should be available.

I'm not really sure what this would be, I haven't used `BABEL_ENV` before, only `NODE_ENV`.

**Comment by jedwards1211** [comment]
`BABEL_ENV` overrides `NODE_ENV` for what babel picks from the `env` section of the options.  It exists so that you can do things like turn code coverage plugins on and off while keeping `NODE_ENV=production`, which people tend to use to turn off warnings and other code that decreases performance.

I think the problem may have been that I wasn't using `babelrc: false` in my `babel-loader` options, but I haven't figure out for sure yet.
