### ISSUE TITLE
latest 2.1.3 rev now fails on css loader chain

### ISSUE THREAD

**Issue by todd-richmond** [amireh/happypack#68]
I updated to to 2.1.3 from 2.1.1 and it can no longer load CSS or SASS. This is most likely due to the large commit to "Robustify extraction of loaders". I'm using webpack 1 and "id" based happypack configuration to support multiple loaders that all share 1 threadpool

    {
        test: /\.css$/,
        exclude: /node_modules/,
        happy: {id: 'css'},
        loader: 'style!css?-autoprefixer&importLoaders=1&-minimize!postcss'
    }

    fatal watch error!!! { Error: Cannot resolve module 'style!css' in src/webui
    at innerCallback (src/webui/node_modules/enhanced-resolve/lib/Resolver.js:91:16)
    at loggingCallbackWrapper (src/webui/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)

**Comment by amireh** [comment]
Uh. That notation is really hard to test, that's why I kept being hesitant on introducing it.

Can you try defining the loaders inline within the plugin configuration and tell me if that works? Would like to know the scope of this.

**Comment by leonid-bauxy** [comment]
It used to work with 2.1.1. Moreso it was the only way to do this, because `happypack` did not accept object notation. I had to stringify all loaders into one string. Now it's broken and there is no other way, but to roll back to 2.1.1 :/

**Comment by alecperkey** [comment]
this notation broke with 2.1.3 also, in case this is helpful. 
```
      createSourceLoader({
        happy: { id: 'sass' },
        test: /\.scss$/,
        loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap'
      }),


      createSourceLoader({
        happy: { id: 'less' },
        test: /\.less$/,
        loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!less?outputStyle=expanded&sourceMap'
      }),

```

**Comment by todd-richmond** [comment]
Unfortunately my config is fairly complex and I used the "id" based Happy configuration scheme to allow me to enable/disable HappyPack globally and on individual loaders with ease. Saved me considerable time for this issue ;) Alecperkey's example is very nearly the same as mine except for localIdentName so I bet any "id" based weback 1.x config will fail in the same manner

The other reason many people need the fully stringified loader config is that we use extract-text plugin in release mode and it seemed to work best with a string. That is a separate issue that was closed, but I'm unable to test for it due to this problem now

**Comment by beckend** [comment]
This also does not work:
`Happy[babelJs]: Version: 2.1.3. Using cache? yes. Threads: 3
fatal watch error!!! { Error: Can't resolve 'react-hot!babel'`

**Comment by amireh** [comment]
This should be fixed on latest master, once you confirm we can push a new release.

**Comment by le0nik** [comment]
@amireh tested it with both `loader` string and `loaders` array. Works fine for me!

**Comment by amireh** [comment]
Great, you can find the patch in v2.2.0. Closing now.

**Comment by todd-richmond** [comment]
verified working - thx!
