### ISSUE TITLE
TypeError: r.forEach is not a function

### ISSUE THREAD

**Issue by moroshko** [amireh/happypack#7]
I get the following error:

![Error](http://dl.dropbox.com/u/1893981/Screenshots/g0id.png)

Here is my webpack config:

    module: {
      loaders: [
        {
          test: /\.js$/,
          loaders: 'happypack/loader',
          include: [
            path.join(__dirname, 'src'),
            path.join(__dirname, 'demo', 'src')
          ]
        }, ...
      ]
    },
    plugins: {
      new HappyPack({
        loaders: [
          {
            path: path.join(__dirname, 'demo', 'src')
          }
        ]
      })
    }

What am I doing wrong?

Also, I'm a bit confused with which paths should be in `module.loaders.include` vs `plugins.happypack.loaders`. Could you elaborate on the difference please?

**Comment by amireh** [comment]
So the error you're seeing is actually from webpack (sadly a bit cryptic) and it's because you're using loader**s** and passing a string instead of an array (under module).

So I'd change it to this:

```javascript
module: {
  loaders: [
    {
      test: /\.js$/,
      loader: 'happypack/loader',
      // or
      loaders: [ 'happypack/loader' ],
      include: [
        path.join(__dirname, 'src'),
        path.join(__dirname, 'demo', 'src')
      ]
    }, ...
  ]
}
```

**Comment by moroshko** [comment]
Thanks a lot for a quick response!

**Comment by amireh** [comment]
@moroshko Glad it worked. Did you get it to work with your loaders, however?

Can you share you results? Which loaders did you use/how did the build time differ? Thanks!

**Comment by moroshko** [comment]
@amireh Sure. I just use Babel:

    new HappyPack({
      loaders: [
        {
          path: path.resolve(__dirname, 'node_modules/babel-loader/index.js'),
          query: '?presets[]=es2015,presets[]=stage-0,presets[]=react'
        }
      ]
    })

I just realised that I probably can use happy pack with other loaders as well (e.g. less, svg), right?

The initial build took ~23s, now it takes ~16s (about 2/3 of the original time).

**Comment by amireh** [comment]
Sadly not the LESS loader, it does weird things that aren't supported by the fake loader API yet. svg loader I'm not sure about.

I'm curious why you didn't benefit more from it though. Using happypack for our babel loader alone chopped off over 300% of the build time. I have to test on more repositories to get more data.

Thanks man.

**Comment by moroshko** [comment]
300% sounds crazy! I wonder if I'm doing something wrong.
Do you mind having a look at my repo:

1. git clone git@github.com:moroshko/react-autosuggest.git
2. cd react-autosuggest
3. git checkout redesign
4. npm install
5. npm start
