### ISSUE TITLE
One `shared thread pool` for multi builds webpack configs.

### ISSUE THREAD

**Issue by nodkz** [amireh/happypack#72]
It's to pity that we can not use `shared thread pools` for multi builds in webpack:

``` js
const bundler = webpack([serverConfig, clientConfig]);
```

When Webpack produces multi builds, it reuse existed modules. Please see that it generate files with same names for client and server. Also the same occurs with js modules.
Totally webpack spends 50 seconds for both builds. Server was ready first because it's smaller. 

```
Time: 41476ms
                               Asset     Size  Chunks             Chunk Names
34665a3c56008a81997f955db71a934c.jpg  3.84 kB          [emitted]
33b41a4660b62eeb7af96e00cc63717e.jpg  83.5 kB          [emitted]
a70d91369984b778c7ae7f004fe2249b.jpg  3.49 kB          [emitted]
304181ab4dc1cfcbe3b7b39475859488.jpg  3.67 kB          [emitted]
5924cb4e7dde56e532533e54b91edcf6.jpg  4.56 kB          [emitted]
ce7b80dd308cf3e14f2ea7eca0c4f2e5.jpg  4.29 kB          [emitted]
ec43e869e127a93be2fc18f7c6f81dd1.jpg  70.1 kB          [emitted]
b11df43845a2422ab99ae7fb8b1c242b.jpg   397 kB          [emitted]
                           server.js  3.94 MB       0  [emitted]  main
webpack built e5e5998f015cdde85cf5 in 49276ms
Time: 49276ms
                               Asset     Size  Chunks             Chunk Names
34665a3c56008a81997f955db71a934c.jpg  3.84 kB          [emitted]
c38059822b8142b5794448ef980373fd.jpg  4.03 kB          [emitted]
a70d91369984b778c7ae7f004fe2249b.jpg  3.49 kB          [emitted]
304181ab4dc1cfcbe3b7b39475859488.jpg  3.67 kB          [emitted]
5924cb4e7dde56e532533e54b91edcf6.jpg  4.56 kB          [emitted]
ce7b80dd308cf3e14f2ea7eca0c4f2e5.jpg  4.29 kB          [emitted]
ec43e869e127a93be2fc18f7c6f81dd1.jpg  70.1 kB          [emitted]
b11df43845a2422ab99ae7fb8b1c242b.jpg   397 kB          [emitted]
        main.js?e5e5998f015cdde85cf5  27.1 MB       0  [emitted]  main
```

And of course, if @joshhunt in [issue55](https://github.com/amireh/happypack/issues/55) has 12 environments benefit of one ThreadPool for all is super important!

**Comment by amireh** [comment]
@nodkz, @hgenru can you guys try out the master branch and see if it fixes these issues? I still have to update the docs with the new changes but basically you need to define a `compilerId` similar to `id` to the loaders/plugins when you have multiple builds going on. This is because webpack doesn't generate any IDs for compilers so it's hard to do implicitly.

Look at the [multi-build example](https://github.com/amireh/happypack/blob/master/examples/multi-build/webpack.config.js) for a sample config.

Let me know!

**Comment by amireh** [comment]
Bump: I'll be making a release that incorporates this change soon - if it's not working, now's the time to tell!

**Comment by amireh** [comment]
Version 3.0.0 is out and contains a fix for this issue. Please be sure to look at the CHANGELOG before upgrading.
