### ISSUE TITLE
happypack is corrupting stats.json when profiling

### ISSUE THREAD

**Issue by delijah** [amireh/happypack#76]
When using the profiling option to export stats to a json, happypack is writing log messages into that json in non json format.

Profiling command: `webpack --profile --json > stats.json`
Docs: http://webpack.github.io/docs/build-performance.html#hints-from-build-stats

Excerpt of my stats.json:
```
Happy[sass]: Version: 2.2.1. Using cache? yes. Threads: 10 (shared pool)
Happy[sass]: Loaded 1 entries from cache. (0 were stale)
Happy[sass]: All set; signalling webpack to proceed.
Happy[rt]: Version: 2.2.1. Using cache? yes. Threads: 10 (shared pool)
Happy[rt]: Loaded 24 entries from cache. (0 were stale)
Happy[rt]: All set; signalling webpack to proceed.
Happy[js]: Version: 2.2.1. Using cache? yes. Threads: 10 (shared pool)
Happy[js]: Loaded 60 entries from cache. (0 were stale)
Happy[js]: All set; signalling webpack to proceed.
{
  "errors": [],
  "warnings": [],
  "version": "1.13.2",
  "hash": "1c2504a329eaafb17778",
  "time": 6905,
  "publicPath": "/",
  "assetsByChunkName": {
    "app": "app.bundle.js"
  },
  ...
```

Would be nice to have happypack messages inside the json structure if this makes sense or no output at all when using the profiling option.

**Comment by Tom910** [comment]
verbose: false and debug: false - should help

**Comment by amireh** [comment]
> Would be nice to have happypack messages inside the json structure if this makes sense or no output at all when using the profiling option.

I'll look at how webpack does this when both `--progress` and `--stats` are specified. If it makes sense, we can make happypack not output anything in that case.

> verbose: false and debug: false - should help

Yeah, I was going to suggest this. This was brought up in an earlier issue https://github.com/amireh/happypack/issues/64

**Comment by delijah** [comment]
Thanks for your responses.

I have imagined that with setting verbose to false the happypack output would disappear. But then i am missing the happypack output when i am not profiling but building or serving.

Would be awesome if happypack would not output anything for profiling.

**Comment by amireh** [comment]
@delijah this should be fixed on master and in the next release (which I'll wait a few days before doing in order to group any changes I get to do in the coming few days.)

**Comment by delijah** [comment]
Awesome! Thanks a lot.

**Comment by amireh** [comment]
Version 3.0.0 is out and contains a fix for this issue. Please be sure to look at the CHANGELOG before upgrading.
