### ISSUE TITLE
TypeError: content.split is not a function

### ISSUE THREAD

**Issue by kraftwer1** [amireh/happypack#79]
**webpack.config.js**
```
...
module: {
    loaders: [
        {test: /\.tsx?$/, loaders: ["happypack/loader"]}
    ]
}
...
plugins: [
    new HappyPack({
        loaders: ["react-hot!awesome-typescript?tsconfig="+tsconfig]
    })
]
...
```

**Error**
```
TypeError: content.split is not a function
    at makeIdentitySourceMap (/Users/me/.../node_modules/react-hot-loader/makeIdentitySourceMap.js:9:11)
```

Did I configure something wrong or is this a problem of `react-hot-loader`?

**Comment by amireh** [comment]
I'm afraid `awesome-typescript` and the `tsloader` loaders aren't supported. See the discussion in #33 and this comment in particular https://github.com/amireh/happypack/issues/33#issuecomment-243629693 since it seems you're in the same boat.

**Comment by kraftwer1** [comment]
Thanks!
