### ISSUE TITLE
infer loaders & use webpack loader resolver

### ISSUE THREAD

**Issue by amireh** [amireh/happypack#8]
instead of requiring absolute paths to loaders, we can reuse webpack loader resolver to find them for us. Then the integration could be as simple as:

```javascript
// @file webpack.config.js
exports.module = {
  loaders: [{
    happy: { id: 'js' },
    test: /\.js$/,
    loaders: [ 'babel?presets[]=es2015', 'react-i18nliner/webpack-loader' ]
  }]
};

exports.plugins = [
  new HappyPack({
    id: 'js',
    inferLoaders: true
  })
]
```

The `inferLoaders` flag will be required because I'd like to keep the original notation supported.

**Comment by jure** [comment]
That looks great! What's the state of this?

**Comment by amireh** [comment]
So, webpack's loader resolver support has been implemented, which was the bigger pain point. The `inferLoaders` option, however, I did implement then decided to drop as it didn't seem to bring much value.

Gonna close this, thanks for reminding me! :grin:

**Comment by jure** [comment]
Ah, so you mean you can just do the e.g. `loaders: [ 'babel?presets[]=es2015', 'react-i18nliner/webpack-loader' ]` and not have to set the inferLoaders option and it will just work?

**Comment by amireh** [comment]
Hmm, you still have to define them on the *plugin*'s config and not the webpack loader's. So you still have to do this:

```javascript
exports.module = {
  loaders: [{
    test: /\.js$/,
    loader: 'happypack/loader?id=js'
  }]
};

exports.plugins = [
  new HappyPack({
    id: 'js',
    loaders: [
      'babel?presets[]=es2015', 'react-i18nliner/webpack-loader'
    ]
  })
]
```

So you basically end up moving the `loaders` property around.

**Comment by jure** [comment]
Right, but that's already much nicer! The README could reflect this new
functionality.

**Comment by amireh** [comment]
The `inferLoaders` option would be very nice to conditionally enable/disable webpack, like say based on an environment variable. Right now it takes a bit of config shuffling to achieve such an effect.

I might revisit this at some point. I will open an issue for updating the readme, thanks!
