### ISSUE TITLE
Cache calls to `emitError` and `emitWarning`

### ISSUE THREAD

**Issue by Strate** [amireh/happypack#85]
Looks like happypack do not cache calls to `emitError` and `emitWarning`. So, usgin cache for linting-loaders (which produces exactly same output as an input, but only emits warnings) is useless. I think we can improve caching here.

**Comment by amireh** [comment]
I'll be doing this the first chance I get to work on this project - it's been around in my head for a while. Thanks for posting!

**Comment by amireh** [comment]
In the light of the change in v4 that [drops caching from happypack](https://github.com/amireh/happypack/blob/master/CHANGELOG.md#400), this ticket is no longer applicable so I'll be closing it. Please feel free to re-open if the issue persists (i.e. it's not related to caching.)
