### ISSUE TITLE
"plugin for the loader '1' could not be found" when two webpack configs are loaded in same node instance

### ISSUE THREAD

**Issue by jedwards1211** [amireh/happypack#88]
Internal global variables always come back to haunt you.  Because the plugin sets its id by default from an internal global counter, if I import two webpack configs in the same node instance (I'm running 2 webpack compilers via the node API rather than CLI), each with a happypack plugin, one plugin gets id `'1'` and the other gets id `'2'`, and then one of them errors out with:

```
Module build failed: AssertionError: HappyPack: plugin for the loader '1' could not be found! Did you forget to add it to the plugin list?
    at Object.HappyLoader (/Users/andy/crater/node_modules/happypack/lib/HappyLoader.js:19:3)
```

Perhaps you could set the plugin id some other way, for instance having a separate counter for each webpack compiler instance and setting the id in a compiler plugin callback?

My workaround for now is to set the `id` manually:

``` js
    new HappyPack({
      id: '1', // https://github.com/amireh/happypack/issues/88
      ...
    })
```

**Comment by amireh** [comment]
That is unfortunate indeed.

I'm doing some work related to multiple compilers to resolve #82 and #72 and since we'll be tracking all the compiler instances in order to solve that issue, I'll just as well tackle this in the same go. We could then have a separate counter for each compiler.

Thanks for reporting!

**Comment by jedwards1211** [comment]
Sounds good, thanks!

**Comment by amireh** [comment]
@jedwards1211 can you try out the master branch and see if it fixes the issue for you?

**Comment by jedwards1211** [comment]
It does, thank you!

**Comment by amireh** [comment]
Thanks for confirming! I'll make a release for this soon, it will be a major increment.

**Comment by amireh** [comment]
Version 3.0.0 is out and contains a fix for this issue. Please be sure to look at the CHANGELOG before upgrading.
