### ISSUE TITLE
pitch loader support

### ISSUE THREAD

**Issue by amireh** [amireh/happypack#9]

**Comment by nifgraup** [comment]
transform-loader support would be valuable as it opens up the possibility of using any browserify transform

**Comment by amireh** [comment]
I see it uses `this.options` (partially supported) and `this.resolve` which isn't too hard to support. Can you show a sample config for a transform loader in use? Preferably the entire webpack.config.js if you can.

**Comment by nifgraup** [comment]
Here is an example using the brfs transform, caching the results for fast webpack --watch

`npm install webpack transform-loader brfs`

webpack.config.js:
```javascript
module.exports = {
  entry: {
    "bundle": "./src/app.js",
  },
  output: {
    filename: "./dist/[name].js",
  },
  module: {
    loaders: [{
      test: /\.js$|\.jsx$/,
      exclude: /node_modules/,
      loaders: ["transform/cacheable?brfs"],
    }],
  },
};
```

**Comment by amireh** [comment]
Thanks!

By the way, there's no longer a need to rely on every loader to provide a caching layer if you use happypack as it will effectively cache the output of any loader (provided they're pure.) So we can just use the regular `transform` loader instead of `transform/cacheable` (I did that with the babel loader.)

**Comment by amireh** [comment]
Gonna close this since pitch loaders should be functional as of `v2.0.0`. Feel free to re-open if this is still not working. Thanks!
