### ISSUE TITLE
Example of DLL usage with happypack

### ISSUE THREAD

**Issue by amilajack** [amireh/happypack#90]
The benchmarks show significant perf wins with DLL's. Webpack does outline how to configure them but it would also be nice to include an example of using them with happypack. I would make a PR for this but I have no idea how to use the DLL plugin.

**Comment by johntran** [comment]
https://github.com/codefoundries/UniversalRelayBoilerplate/issues/138

See if this helps. :)

**Comment by amireh** [comment]
I think i've submitted a sample config for this use case over [here](https://github.com/erikras/react-redux-universal-hot-example/pull/1201) - maybe that helps. We've been using a similar setup at work and it's been working fine.

**Comment by amireh** [comment]
don't feel like doing this, can accept PRs. This isn't really a happypack issue (the two can be used together by following each's documentation)
