### ISSUE TITLE
Doesn't work with webpack v2.1.0-beta.23+

### ISSUE THREAD

**Issue by 7rulnik** [amireh/happypack#91]
[Webpack v2.1.0-beta.23](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.24) released two days ago. Unfortunately happypack don't work with it.

Here some breaking changes with [loaders declaration](https://github.com/webpack/webpack.js.org/blob/develop/content/how-to/upgrade-from-webpack-1.md#moduleloaders-is-now-modulerules), but old syntax is still valid. 

`happy: { id: 'js' }` now may be part of options in loader.

But if I run webpack I see this error:

```
Uncaught Error: Module parse failed: …/node_modules/happypack/loader.js?id=js!/…/app/app.js Unexpected token (60:4)
You may need an appropriate loader to handle this file type.
```

**Comment by STRML** [comment]
Can be fixed in your webpack config with something like (keep `happy` in your loaders):

```js
    // Go through each loader that has a 'happy: {id: string}' and add
    // a HappyPack plugin to render it in parallel.
    ...loaders.filter((l) => l.happy).map((l) => {
      const {loader, happy, options = {}} = l;
      delete l.happy;
      delete l.options;
      l.loader = 'happypack/loader';
      options.id = happy.id;
      return new HappyPack({
        loaders: [{path: loader, options: qs.stringify(options)}],
      });
    }),

**Comment by amireh** [comment]
I think the right move forward is to (re)drop this configuration style and only support specifying loaders on the plugin directly. This has caused too much trouble to be worth it (and indeed, I can't see many workarounds that would look different than @STRML's.)

**Comment by eisisig** [comment]
What about LoaderOptionsPlugin  https://gist.github.com/eisisig/850e1e1adbf1f38c5618bd0cfa5d37f0#loader-options--minimize

**Comment by amireh** [comment]
Like I mentioned elsewhere, I won't be looking at webpack 2 support until it's out of beta status since there's so much churn right now. We'll see how it ends up looking. :)

**Comment by moimikey** [comment]
i got this to work perfectly with webpack 2. here's what i did:

```js
  plugins: [
      new HappyPackPlugin({
        loaders: ['babel'],
        id: 'js',
        threads: 2
      })
  ]
```

```js
      module: {
      rules: [{
        test: /\.js$/,
        use: ['babel'], // this seemed to be fine without using the happypack loader
        include: OPTIONS.srcDir,
        options: {
          happy: {
            id: 'js'
          }
        }
      }
```

**Comment by eisisig** [comment]
It seems to work fine like this with my setup if it helps anybody.

```js
{
    test: /\.js$/,
    // Need to specify the loader by file as it doesn't confirm to new loader naming rules
    loader: join(local_node_modules, 'happypack', 'loader.js'),
    options: {
        id: 'js'
    },
}
```
```js
new HappyPackPlugin({
    loaders: [ 'babel-loader?' + JSON.stringify(babelQuery) ],
    id: 'js',
    threads: 4,
}),
```
```json
{
    "happypack": "^3.0.0",
    "webpack": "2.1.0-beta.27",
    "webpack-dev-server": "2.1.0-beta.12",
}
```

**Comment by o2dazone** [comment]
@amireh with Webpack 2.2 in Release Candidate status, any foreseeable plans to support it with HappyPack?

**Comment by amireh** [comment]
@o2dazone I'll be now closely following the progress and take a look at what needs updating. Might be worth creating a wiki page or use that new github project feature to keep track of what's broken.

**Comment by todd-richmond** [comment]
I tried option arguments as well as forcing a file loader.js w/o luck in Webpack 2 RC.3 which was finally stable enough to compile my complex application. Adding HappyPack causes

"You may need an appropriate loader to handle this file type" for both jsx and sass files

**Comment by amireh** [comment]
Version 3.0.3 has many fixes that should improve webpack2 compatibility so this issue can be considered resolved.

If you come across particular issues using webpack2, feel free to open a specific ticket!
