### ISSUE TITLE
less + ExtractTextPlugin hangs

### ISSUE THREAD

**Issue by kfeinUI** [amireh/happypack#93]
I've found the prior recommended discussion around getting less to work with HappyPack and applied the suggested configuration. With the debug output enabled, it shows a number of messages indicating that the various less files have changed and that it is recompiling. Nothing happens from there though. The build just hangs. Any thoughts or suggestions?
- Node 6.6.0 on Windows
- HappyPack 2.2.1
- Webpack 1.13.2
- Rest of the plugins are the latest. Realize there are many points of failure. Can dive deeper if need be.
- Similar config for *.css with just the css-loader works.

```
const extractStyles = new ExtractTextPlugin('[name].css', {allChunks: true});

Loader config
-------------
{
test: /\.less$/,
loader: extractStyles.extract('style', 'happypack/loader?id=lessHappy')
...
}

Plugin config
--------------
new HappyPack({
    id: 'lessHappy',
    loaders: ['css?-url&-autoprefixer&sourceMap', 'less?sourceMap'],
    verbose: true,
    debug: true
})
```

Been trying all kinds of variations of feeding in the loaders, but to no avail. I see that there were recent changes to get less working (though perhaps not in combination with ExtractTextPlugin). Thanks in advance!

**Comment by amireh** [comment]
I have a feeling it's related to Windows, since the hang you describe was also mentioned in https://github.com/amireh/happypack/issues/70 (although with different loaders.)

I'll try this on Linux and see if we can verify that.

**Comment by csvan** [comment]
Confirming that this is an issue on Windows 7. I have not been able to replicate it on Ubuntu.

**Comment by kfeinUI** [comment]
Still an issue with Webpack 2.2.1 and happypack 3.0.3 along with the latest of everything else.

**Comment by imsontosh** [comment]
Still an issue with Webpack 2.2.1 and happypack 3.0.3.

**Comment by amireh** [comment]
Can you try this using `4.0.0-beta.4` and see if it's fixed? The hang on windows issue was resolved in that release and I'm guessing this is the same problem.

**Comment by kfeinUI** [comment]
Nice. It's working! :shipit:

**Comment by amireh** [comment]
Great, thanks for confirming!
