### ISSUE TITLE
Webpack 2.1.0-beta.25: babel not using configuration

### ISSUE THREAD

**Issue by wmertens** [amireh/happypack#94]
I had Happypack working fine with Webpack 2.1-b4. When I tried upgrading to 2.1-b25, happypack-loaded babel files no longer used the `stage-2` preset defined in `.babelrc`. Replacing the happypack loader with babel makes it work fine.

Even when I add the query to the babel loader in the HappyPack plugin setup, it still ignores the `stage-2` preset.

**Comment by wmertens** [comment]
never mind, it is a different problem, perhaps hidden due to caching. reverting to b4 does not make a difference.

**Comment by brabeji** [comment]
@wmertens I have the same problem. Have you been able to resolve this?

**Comment by IanVS** [comment]
I'm seeing the same.  It's like the `.babelrc` is not being respected.
