### ISSUE TITLE
 TypeError : queryString.match is not a function

### ISSUE THREAD

**Issue by yoohan-dex** [amireh/happypack#98]
```
Module build failed: TypeError: queryString.match is not a function
    at getId (C:\Users\yao46\Documents\Workspace\linkwo\node_modules\happypack\lib\HappyLoader.js:62:23)
    at Object.HappyLoader (C:\Users\yao46\Documents\Workspace\linkwo\node_modules\happypack\lib\HappyLoader.js:6:12)
 @ multi bundle
```

it looks like something does not match the 'webpack' API ?

**Comment by amireh** [comment]
Hmm, for some reason the query isn't a string. Can you show me the loader config? Is this webpack 2?

**Comment by yoohan-dex** [comment]
```
const babelQuery = {
  cacheDirectory: true,
  plugins: [
    ['transform-decorators-legacy'],
    ['inline-import'],
    ['react-transform', {
      transforms: [{
        transform: 'react-transform-hmr',
        imports: ['react'],
        locals: ['module'],
      }, {
        transform: 'react-transform-catch-errors',
        imports: ['react', 'redbox-react'],
      }],
    }],
  ],
};

plugins: [
  new HappyPack({
      loaders: ['babel'],
      threads: 4
    })
]
```
@amireh

**Comment by amireh** [comment]
Hmm, yeah but I meant the query being passed to your happypack loader. How are your module loaders configured? (`webpackConfig.module.loaders`)

**Comment by amireh** [comment]
Oh I see it now. Yeah that's not how it works, you need to pass your babelQuery inside your HappyPack plugin. It's documented in the readme.

```javascript
new HappyPack({
  loaders: [{ loader: 'babel', query: babelQuery }]
})
```

**Comment by yoohan-dex** [comment]
oh .. sorry my post is not clear 
thank for you help!!
you are so nice !

but after accepting your solution , I got another problem ...

` [Error] AssertionError: HappyPack[1]: Loader must have a @path property or be a string.`

```
//modules

    loaders: [{
      test: /\.js?$/,
      loader: 'happypack/loader',
      include: sources,
    },
```
```
//plugins
plugins: [
    new HappyPack({
      loaders: [{loader: 'babel', query: babelQuery}],
      threads: 4,
      cachePath: '/',
    }),
]
```

my `babelquery` has not changed

**Comment by amireh** [comment]
Oh! I thought we fixed that. Try changing `loader` to `path` in my example above:

```javascript
new HappyPack({
  loaders: [{ path: 'babel', query: babelQuery }]
})
```

And you're welcome! Hope that helps.

**Comment by yoohan-dex** [comment]
your example I have tried , still, don't work for me .

```
validate: function(value) {
        if (!Array.isArray(value)) {
          return 'Loaders must be an array!';
        }
        else if (value.length === 0) {
          return 'You must specify at least one loader!';
        }
        else if (value.some(function(loader) {
          return typeof loader !== 'string' && !loader.path;
        })) {
          return 'Loader must have a @path property or be a string.'
        }
      },
```
I see the source code that will validate the array of loaders . if not a string , will report a `@path` error .

maybe your example is not suitable?

**Comment by amireh** [comment]
Yeah but why are you hitting that error? It only verifies that `path` is a String but not the query. `path` should be `babel` and `query` would be `babelQuery`. Is that not working? (Please check https://github.com/amireh/happypack/issues/98#issuecomment-253971815 again)

**Comment by yoohan-dex** [comment]
@amireh 
I think that was about something like webpack2 's API has changed 
I can handle the `@path` error but the `happypack` can handle transform my js code anyway.
maybe you should consider rebuilding the project  =v=

**Comment by amireh** [comment]
Until webpack 2 is out of beta I won't be putting any time into supporting it.

**Comment by yoohan-dex** [comment]
😂😂I am also looking forward the steady webpack2



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by sea129** [comment]
got same error with "webpack": "^2.1.0-beta.25", but it was alright with beta.4

**Comment by MikaAK** [comment]
With webpack `2.1.0-beta.27`  a workaround is set your loader to 
```javascript
{
  loaders: ['happypack/loader'],
  options: 'id=js'
}
```

**Comment by amireh** [comment]
This should be fixed in the upcoming release since we'll be supporting `options` for loaders. Thanks guys.

**Comment by yoohan-dex** [comment]
@amireh thanks
